# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"ycolumn"}{$SasPackage}{"Parameters"}="node4.html#288";
$SasIndex{"Parameters"}{"outset"}{$SasPackage}{"Parameters"}="node4.html#274";
$SasIndex{"Tasks"}{"dal"}{$SasPackage}{"Errors"}="node5.html#304";
$SasIndex{"Tasks"}{"ds9tocxc"}{$SasPackage}{"Description"}="node3.html#258";
$SasIndex{"Parameters"}{"xcolumn"}{$SasPackage}{"Parameters"}="node4.html#281";
$SasIndex{"Errors"}{"InvalidRegion"}{$SasPackage}{"Errors"}="node5.html#299";

1; # This must be the last line
