# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"maxrmsres"}{$SasPackage}{"Parameters"}="node48.html#579";
$SasIndex{"Parameters"}{"alignaxes"}{$SasPackage}{"Parameters"}="node48.html#558";
$SasIndex{"Parameters"}{"maxradec"}{$SasPackage}{"Parameters"}="node48.html#572";
$SasIndex{"Warnings"}{"Failed to release memory for : name"}{$SasPackage}{"Errors"}="node49.html#595";
$SasIndex{"Warnings"}{"two sources matched in same OSW"}{$SasPackage}{"Errors"}="node49.html#600";
$SasIndex{"Parameters"}{"usecat"}{$SasPackage}{"Parameters"}="node48.html#551";
$SasIndex{"Errors"}{"Could not allocate memory for : name"}{$SasPackage}{"Errors"}="node49.html#590";
$SasIndex{"Parameters"}{"sourcelistsets"}{$SasPackage}{"Parameters"}="node48.html#529";
$SasIndex{"Warnings"}{"colExist"}{$SasPackage}{"Errors"}="node49.html#605";
$SasIndex{"Parameters"}{"nsigma"}{$SasPackage}{"Parameters"}="node48.html#544";
$SasIndex{"Parameters"}{"catfile"}{$SasPackage}{"Parameters"}="node48.html#565";
$SasIndex{"Parameters"}{"outset"}{$SasPackage}{"Parameters"}="node48.html#537";

1; # This must be the last line
