# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"device"}{$SasPackage}{"Parameters"}="node5.html#375";
$SasIndex{"Errors"}{"Plot file already exists"}{$SasPackage}{"Errors"}="node6.html#422";
$SasIndex{"Warnings"}{"Keyword HDUCLAS2 missing"}{$SasPackage}{"Errors"}="node6.html#442";
$SasIndex{"Parameters"}{"plotfile"}{$SasPackage}{"Parameters"}="node5.html#382";
$SasIndex{"Errors"}{"badDevice"}{$SasPackage}{"Errors"}="node6.html#407";
$SasIndex{"Warnings"}{"Average counts per bin less than 1"}{$SasPackage}{"Errors"}="node6.html#452";
$SasIndex{"Errors"}{"No plot file supplied"}{$SasPackage}{"Errors"}="node6.html#417";
$SasIndex{"Warnings"}{"Keyword TCUNI1 missing"}{$SasPackage}{"Errors"}="node6.html#447";
$SasIndex{"Parameters"}{"group"}{$SasPackage}{"Parameters"}="node5.html#368";
$SasIndex{"Parameters"}{"rebin"}{$SasPackage}{"Parameters"}="node5.html#389";
$SasIndex{"Tasks"}{"evselect"}{$SasPackage}{"Parameters"}="node5.html#346";
$SasIndex{"Tasks"}{"rgsregion"}{$SasPackage}{"Input Files"}="node7.html#461";
$SasIndex{"Warnings"}{"Rebin requested to be less than 1"}{$SasPackage}{"Errors"}="node6.html#432";
$SasIndex{"Parameters"}{"spectrumsets"}{$SasPackage}{"Parameters"}="node5.html#337";
$SasIndex{"Tasks"}{"rgsproc"}{$SasPackage}{"Parameters"}="node5.html#350";
$SasIndex{"Errors"}{"Incorrect number of spectrum sets given"}{$SasPackage}{"Errors"}="node6.html#412";
$SasIndex{"Parameters"}{"sourceid"}{$SasPackage}{"Parameters"}="node5.html#361";
$SasIndex{"Warnings"}{"Surplus filename"}{$SasPackage}{"Errors"}="node6.html#427";
$SasIndex{"Parameters"}{"mincounts"}{$SasPackage}{"Parameters"}="node5.html#396";
$SasIndex{"Warnings"}{"Rebinning results in less than 5 bins"}{$SasPackage}{"Errors"}="node6.html#437";
$SasIndex{"Parameters"}{"sourcelistset"}{$SasPackage}{"Parameters"}="node5.html#354";

1; # This must be the last line
