# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Tasks"}{"hkstrip"}{$SasPackage}{"Description"}="node3.html#290";
$SasIndex{"Parameters"}{"useodf"}{$SasPackage}{"Parameters"}="node4.html#333";
$SasIndex{"Parameters"}{"table"}{$SasPackage}{"Parameters"}="node4.html#323";
$SasIndex{"Blocks"}{"PERIODIC_HK"}{$SasPackage}{"Parameters"}="node4.html#331";
$SasIndex{"Errors"}{"BadODFname"}{$SasPackage}{"Errors"}="node5.html#344";
$SasIndex{"Parameters"}{"paramnames"}{$SasPackage}{"Parameters"}="node4.html#313";
$SasIndex{"Columns"}{"TIME"}{$SasPackage}{"Parameters"}="node4.html#321";
$SasIndex{"Parameters"}{"outset"}{$SasPackage}{"Parameters"}="node4.html#304";
$SasIndex{"Parameters"}{"set"}{$SasPackage}{"Parameters"}="node4.html#297";

1; # This must be the last line
