# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"outset"}{$SasPackage}{"Parameters"}="node3.html#252";
$SasIndex{"Parameters"}{"tempset"}{$SasPackage}{"Parameters"}="node3.html#259";
$SasIndex{"Parameters"}{"inset"}{$SasPackage}{"Parameters"}="node3.html#245";

1; # This must be the last line
