# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"imagesets"}{$SasPackage}{"Parameters"}="node4.html#278";
$SasIndex{"Errors"}{"4 image files are required"}{$SasPackage}{"Errors"}="node5.html#306";
$SasIndex{"Errors"}{"Invalid WINDOWXO value (x) for file name"}{$SasPackage}{"Errors"}="node5.html#311";
$SasIndex{"Errors"}{"Invalid y-image size"}{$SasPackage}{"Errors"}="node5.html#301";
$SasIndex{"Warnings"}{"Invalid BINBPE value for file name"}{$SasPackage}{"Errors"}="node5.html#336";
$SasIndex{"Errors"}{"Invalid WINDOWYO value (x) for file name"}{$SasPackage}{"Errors"}="node5.html#321";
$SasIndex{"Errors"}{"Invalid WINDOWDX value (x) for file name"}{$SasPackage}{"Errors"}="node5.html#326";
$SasIndex{"Parameters"}{"outset"}{$SasPackage}{"Parameters"}="node4.html#285";
$SasIndex{"Warnings"}{"Invalid WINDOWDY value (x) for file name"}{$SasPackage}{"Errors"}="node5.html#331";
$SasIndex{"Errors"}{"2 FILES (name1 and name2) have identical WINDOWX0 values"}{$SasPackage}{"Errors"}="node5.html#316";
$SasIndex{"Errors"}{"Invalidx-image size"}{$SasPackage}{"Errors"}="node5.html#296";

1; # This must be the last line
