# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Columns"}{"BADFLAG"}{$SasPackage}{"Output Files"}="node7.html#666";
$SasIndex{"Columns"}{"ENERGY"}{$SasPackage}{"Input Files"}="node6.html#622";
$SasIndex{"Parameters"}{"withbadpixset"}{$SasPackage}{"Parameters"}="node4.html#476";
$SasIndex{"Warnings"}{"BadPixNonsense"}{$SasPackage}{"Errors"}="node5.html#591";
$SasIndex{"Warnings"}{"BadPixIncorrect"}{$SasPackage}{"Errors"}="node5.html#581";
$SasIndex{"Parameters"}{"badpixalgo"}{$SasPackage}{"Parameters"}="node4.html#500";
$SasIndex{"Parameters"}{"withadvisory"}{$SasPackage}{"Parameters"}="node4.html#493";
$SasIndex{"Columns"}{"YEXTENT"}{$SasPackage}{"Output Files"}="node7.html#661";
$SasIndex{"Parameters"}{"pixsharpness"}{$SasPackage}{"Parameters"}="node4.html#542";
$SasIndex{"Attributes"}{"EXP_ID"}{$SasPackage}{"Input Files"}="node6.html#638";
$SasIndex{"Warnings"}{"BadPixDuplicates"}{$SasPackage}{"Errors"}="node5.html#576";
$SasIndex{"Attributes"}{"ABUTTED"}{$SasPackage}{"Output Files"}="node7.html#654";
$SasIndex{"Columns"}{"RAWY"}{$SasPackage}{"Input Files"}="node6.html#619";
$SasIndex{"Attributes"}{"CCDOCB"}{$SasPackage}{"Input Files"}="node6.html#610";
$SasIndex{"Columns"}{"CHIPY"}{$SasPackage}{"Output Files"}="node7.html#658";
$SasIndex{"Columns"}{"CHIPX"}{$SasPackage}{"Output Files"}="node7.html#656";
$SasIndex{"Blocks"}{"BADPIXn"}{$SasPackage}{"Home Page"}="rgsbadpix.html#445";
$SasIndex{"Blocks"}{"EXPOSURE"}{$SasPackage}{"Description"}="node3.html#467";
$SasIndex{"Attributes"}{"RAWY"}{$SasPackage}{"Input Files"}="node6.html#612";
$SasIndex{"Warnings"}{"InvalidCoordinates"}{$SasPackage}{"Errors"}="node5.html#571";
$SasIndex{"Columns"}{"FRAME"}{$SasPackage}{"Input Files"}="node6.html#594";
$SasIndex{"Parameters"}{"colsharpness"}{$SasPackage}{"Parameters"}="node4.html#549";
$SasIndex{"Columns"}{"SHAPE"}{$SasPackage}{"Input Files"}="node6.html#626";
$SasIndex{"Parameters"}{"ccdset"}{$SasPackage}{"Parameters"}="node4.html#469";
$SasIndex{"EventAttributes"}{"IN_BAD_FRAME"}{$SasPackage}{"Description"}="node3.html#463";
$SasIndex{"Attributes"}{"INSTRUME"}{$SasPackage}{"Input Files"}="node6.html#634";
$SasIndex{"Parameters"}{"withfoundhot"}{$SasPackage}{"Parameters"}="node4.html#514";
$SasIndex{"Attributes"}{"WINDOWDX"}{$SasPackage}{"Input Files"}="node6.html#604";
$SasIndex{"Parameters"}{"embadpixalgo"}{$SasPackage}{"Parameters"}="node4.html#507";
$SasIndex{"Attributes"}{"OBS_ID"}{$SasPackage}{"Input Files"}="node6.html#636";
$SasIndex{"Columns"}{"FLAG"}{$SasPackage}{"Description"}="node3.html#465";
$SasIndex{"Parameters"}{"colnoiselimit"}{$SasPackage}{"Parameters"}="node4.html#535";
$SasIndex{"Columns"}{"CCDNODE"}{$SasPackage}{"Input Files"}="node6.html#624";
$SasIndex{"Blocks"}{"BADPIX1"}{$SasPackage}{"Output Files"}="node7.html#642";
$SasIndex{"Attributes"}{"CCDNODE"}{$SasPackage}{"Output Files"}="node7.html#644";
$SasIndex{"Tasks"}{"rgsbadpix"}{$SasPackage}{"Description"}="node3.html#447";
$SasIndex{"Columns"}{"TYPE"}{$SasPackage}{"Output Files"}="node7.html#664";
$SasIndex{"Parameters"}{"keepcool"}{$SasPackage}{"Parameters"}="node4.html#521";
$SasIndex{"Blocks"}{"PIXELS"}{$SasPackage}{"Errors"}="node5.html#563";
$SasIndex{"Attributes"}{"TELESCOP"}{$SasPackage}{"Input Files"}="node6.html#632";
$SasIndex{"Columns"}{"GRADE"}{$SasPackage}{"Input Files"}="node6.html#629";
$SasIndex{"Attributes"}{"CCDID"}{$SasPackage}{"Input Files"}="node6.html#608";
$SasIndex{"Parameters"}{"pixnoiselimit"}{$SasPackage}{"Parameters"}="node4.html#528";
$SasIndex{"Warnings"}{"MissingFrames"}{$SasPackage}{"Errors"}="node5.html#560";
$SasIndex{"Blocks"}{"BADPIX0"}{$SasPackage}{"Output Files"}="node7.html#640";
$SasIndex{"Warnings"}{"BadPixDiscrepancy"}{$SasPackage}{"Errors"}="node5.html#586";
$SasIndex{"Attributes"}{"WINDOWDY"}{$SasPackage}{"Input Files"}="node6.html#606";
$SasIndex{"Attributes"}{"WINDOWX0"}{$SasPackage}{"Input Files"}="node6.html#600";
$SasIndex{"Parameters"}{"badpixset"}{$SasPackage}{"Parameters"}="node4.html#486";
$SasIndex{"Columns"}{"RAWX"}{$SasPackage}{"Input Files"}="node6.html#617";
$SasIndex{"EventAttributes"}{"NEXT_TO_BADPIX"}{$SasPackage}{"Output Files"}="node7.html#678";
$SasIndex{"Attributes"}{"WINDOWY0"}{$SasPackage}{"Input Files"}="node6.html#602";

1; # This must be the last line
