# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"thxset"}{$SasPackage}{"Parameters"}="node4.html#314";
$SasIndex{"Warnings"}{"deAllocError"}{$SasPackage}{"Errors"}="node5.html#335";
$SasIndex{"Parameters"}{"timefactor"}{$SasPackage}{"Parameters"}="node4.html#300";
$SasIndex{"Parameters"}{"samplefactor"}{$SasPackage}{"Parameters"}="node4.html#293";
$SasIndex{"Errors"}{"badFileMode"}{$SasPackage}{"Errors"}="node5.html#325";
$SasIndex{"Parameters"}{"set"}{$SasPackage}{"Parameters"}="node4.html#307";
$SasIndex{"Errors"}{"allocError"}{$SasPackage}{"Errors"}="node5.html#330";

1; # This must be the last line
