# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Warnings"}{"The spectrum is badly affected by Mod-8 noise / coincidence loss"}{$SasPackage}{"Errors"}="node5.html#456";
$SasIndex{"Parameters"}{"set"}{$SasPackage}{"Parameters"}="node4.html#348";
$SasIndex{"Parameters"}{"spectrumhalfwidth"}{$SasPackage}{"Parameters"}="node4.html#400";
$SasIndex{"Parameters"}{"bkgoffsetright"}{$SasPackage}{"Parameters"}="node4.html#422";
$SasIndex{"Parameters"}{"bkgwidthright"}{$SasPackage}{"Parameters"}="node4.html#429";
$SasIndex{"Parameters"}{"sourcelistset"}{$SasPackage}{"Parameters"}="node4.html#356";
$SasIndex{"Parameters"}{"regionfile"}{$SasPackage}{"Parameters"}="node4.html#371";
$SasIndex{"Parameters"}{"spectrumsmoothlength"}{$SasPackage}{"Parameters"}="node4.html#436";
$SasIndex{"Parameters"}{"outspectralistset"}{$SasPackage}{"Parameters"}="node4.html#385";
$SasIndex{"Warnings"}{"Could not find any compatible blocks in set"}{$SasPackage}{"Errors"}="node5.html#461";
$SasIndex{"Parameters"}{"outset"}{$SasPackage}{"Parameters"}="node4.html#364";
$SasIndex{"Tasks"}{"omgprep"}{$SasPackage}{"Description"}="node3.html#340";
$SasIndex{"Tasks"}{"omdetect"}{$SasPackage}{"Description"}="node3.html#344";
$SasIndex{"Parameters"}{"bkgoffsetleft"}{$SasPackage}{"Parameters"}="node4.html#408";
$SasIndex{"Parameters"}{"extractfieldspectra"}{$SasPackage}{"Parameters"}="node4.html#392";
$SasIndex{"Parameters"}{"extractionmode"}{$SasPackage}{"Parameters"}="node4.html#444";
$SasIndex{"Parameters"}{"spectraregionfile"}{$SasPackage}{"Parameters"}="node4.html#378";
$SasIndex{"Parameters"}{"bkgwidthleft"}{$SasPackage}{"Parameters"}="node4.html#415";

1; # This must be the last line
