# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Tasks"}{"dsplot"}{$SasPackage}{"Description"}="node3.html#263";
$SasIndex{"Parameters"}{"plotter"}{$SasPackage}{"Parameters"}="node4.html#272";
$SasIndex{"Tasks"}{"dstoplot"}{$SasPackage}{"Description"}="node3.html#257";

1; # This must be the last line
