# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"interpolate"}{$SasPackage}{"Parameters"}="node4.html#307";
$SasIndex{"Parameters"}{"thxset"}{$SasPackage}{"Parameters"}="node4.html#293";
$SasIndex{"Parameters"}{"nphset"}{$SasPackage}{"Parameters"}="node4.html#300";
$SasIndex{"Errors"}{"Wrong datamodes for input files"}{$SasPackage}{"Errors"}="node5.html#318";
$SasIndex{"Parameters"}{"set"}{$SasPackage}{"Parameters"}="node4.html#286";

1; # This must be the last line
