# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"rawfile"}{$SasPackage}{"Parameters"}="node4.html#278";
$SasIndex{"Parameters"}{"strict"}{$SasPackage}{"Parameters"}="node4.html#299";
$SasIndex{"Parameters"}{"useS2K"}{$SasPackage}{"Parameters"}="node4.html#292";
$SasIndex{"Errors"}{"No data File"}{$SasPackage}{"Errors"}="node5.html#318";
$SasIndex{"Parameters"}{"cachedir"}{$SasPackage}{"Parameters"}="node4.html#306";
$SasIndex{"Warnings"}{"OBT reset"}{$SasPackage}{"Errors"}="node5.html#323";
$SasIndex{"Parameters"}{"outfile"}{$SasPackage}{"Parameters"}="node4.html#285";

1; # This must be the last line
