# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"eventset"}{$SasPackage}{"Parameters"}="node4.html#422";
$SasIndex{"Errors"}{"badInstrument"}{$SasPackage}{"Errors"}="node5.html#512";
$SasIndex{"Attributes"}{"CCDID"}{$SasPackage}{"Input Files"}="node6.html#560";
$SasIndex{"Tasks"}{"rgsbadpix"}{$SasPackage}{"Comments"}="node9.html#612";
$SasIndex{"Attributes"}{"OBS_ID"}{$SasPackage}{"Input Files"}="node6.html#584";
$SasIndex{"Parameters"}{"badpixset"}{$SasPackage}{"Parameters"}="node4.html#455";
$SasIndex{"Tasks"}{"epevents"}{$SasPackage}{"Output Files"}="node7.html#602";
$SasIndex{"Warnings"}{"badBadpixfindFile"}{$SasPackage}{"Errors"}="node5.html#532";
$SasIndex{"Attributes"}{"WINDOWDX"}{$SasPackage}{"Input Files"}="node6.html#568";
$SasIndex{"Attributes"}{"INSTRUME"}{$SasPackage}{"Input Files"}="node6.html#556";
$SasIndex{"Columns"}{"YEXTENT"}{$SasPackage}{"Output Files"}="node7.html#596";
$SasIndex{"Columns"}{"RAWX"}{$SasPackage}{"Output Files"}="node7.html#592";
$SasIndex{"Attributes"}{"WINDOWY0"}{$SasPackage}{"Input Files"}="node6.html#566";
$SasIndex{"Attributes"}{"CCDNODE"}{$SasPackage}{"Input Files"}="node6.html#562";
$SasIndex{"Warnings"}{"BPTcode"}{$SasPackage}{"Errors"}="node5.html#527";
$SasIndex{"Parameters"}{"emptyextension"}{$SasPackage}{"Parameters"}="node4.html#467";
$SasIndex{"Attributes"}{"WINDOWX0"}{$SasPackage}{"Input Files"}="node6.html#564";
$SasIndex{"Tasks"}{"badpixfind"}{$SasPackage}{"Description"}="node3.html#398";
$SasIndex{"Attributes"}{"WINDOWDY"}{$SasPackage}{"Input Files"}="node6.html#570";
$SasIndex{"Blocks"}{"BADPIX"}{$SasPackage}{"Description"}="node3.html#418";
$SasIndex{"Parameters"}{"withoutset"}{$SasPackage}{"Parameters"}="node4.html#484";
$SasIndex{"Tasks"}{"emevents"}{$SasPackage}{"Input Files"}="node6.html#552";
$SasIndex{"Parameters"}{"outset"}{$SasPackage}{"Parameters"}="node4.html#494";
$SasIndex{"Columns"}{"RAWY"}{$SasPackage}{"Output Files"}="node7.html#594";
$SasIndex{"Attributes"}{"EXP_ID"}{$SasPackage}{"Input Files"}="node6.html#582";
$SasIndex{"Parameters"}{"getotherbadpix"}{$SasPackage}{"Parameters"}="node4.html#436";
$SasIndex{"Errors"}{"noBadpixModes"}{$SasPackage}{"Errors"}="node5.html#517";
$SasIndex{"Errors"}{"badExtension"}{$SasPackage}{"Errors"}="node5.html#507";
$SasIndex{"Attributes"}{"QUADRANT"}{$SasPackage}{"Input Files"}="node6.html#558";
$SasIndex{"Parameters"}{"getnewbadpix"}{$SasPackage}{"Parameters"}="node4.html#443";
$SasIndex{"Parameters"}{"getuplnkbadpix"}{$SasPackage}{"Parameters"}="node4.html#429";
$SasIndex{"Attributes"}{"TELESCOP"}{$SasPackage}{"Input Files"}="node6.html#576";
$SasIndex{"Warnings"}{"overwriteBadpix"}{$SasPackage}{"Errors"}="node5.html#544";
$SasIndex{"Tasks"}{"badpix"}{$SasPackage}{"Home Page"}="badpix.html#386";
$SasIndex{"Columns"}{"BADFLAG"}{$SasPackage}{"Output Files"}="node7.html#600";
$SasIndex{"Parameters"}{"windowfilter"}{$SasPackage}{"Parameters"}="node4.html#477";
$SasIndex{"Tasks"}{"epframes"}{$SasPackage}{"Input Files"}="node6.html#548";
$SasIndex{"Columns"}{"TYPE"}{$SasPackage}{"Output Files"}="node7.html#598";

1; # This must be the last line
