# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Tasks"}{"poscorr3xmm"}{$SasPackage}{"Description"}="node3.html#268";
$SasIndex{"Errors"}{"AlreadyCorrected"}{$SasPackage}{"Errors"}="node7.html#283";
$SasIndex{"Parameters"}{"srclist"}{$SasPackage}{"Parameters"}="node6.html#272";

1; # This must be the last line
