# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Warnings"}{"You are combining images from the same exposure"}{$SasPackage}{"Errors"}="node10.html#705";
$SasIndex{"Parameters"}{"di"}{$SasPackage}{"Parameters"}="node5.html#677";
$SasIndex{"Parameters"}{"maxdx"}{$SasPackage}{"Parameters"}="node5.html#663";
$SasIndex{"Parameters"}{"minfraction"}{$SasPackage}{"Parameters"}="node5.html#656";
$SasIndex{"Parameters"}{"mincorr"}{$SasPackage}{"Parameters"}="node5.html#642";
$SasIndex{"Parameters"}{"mosaicedset"}{$SasPackage}{"Parameters"}="node5.html#621";
$SasIndex{"Warnings"}{"You are combining identical images"}{$SasPackage}{"Errors"}="node10.html#695";
$SasIndex{"Parameters"}{"nsigma"}{$SasPackage}{"Parameters"}="node5.html#649";
$SasIndex{"Parameters"}{"numintervals"}{$SasPackage}{"Parameters"}="node5.html#670";
$SasIndex{"Parameters"}{"minnumpixels"}{$SasPackage}{"Parameters"}="node5.html#684";
$SasIndex{"Parameters"}{"binaxis"}{$SasPackage}{"Parameters"}="node5.html#635";
$SasIndex{"Parameters"}{"correlset"}{$SasPackage}{"Parameters"}="node5.html#628";
$SasIndex{"Warnings"}{"Non of the images are astrometry-corrected"}{$SasPackage}{"Errors"}="node10.html#715";
$SasIndex{"Warnings"}{"<"}{$SasPackage}{"Errors"}="node10.html#700";
$SasIndex{"Parameters"}{"imagesets"}{$SasPackage}{"Parameters"}="node5.html#614";

1; # This must be the last line
