# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"imageset"}{$SasPackage}{"Parameters"}="node3.html#266";
$SasIndex{"Parameters"}{"outcol"}{$SasPackage}{"Parameters"}="node3.html#298";
$SasIndex{"Parameters"}{"ycol"}{$SasPackage}{"Parameters"}="node3.html#289";
$SasIndex{"Parameters"}{"srclisttab"}{$SasPackage}{"Parameters"}="node3.html#273";
$SasIndex{"Parameters"}{"xcol"}{$SasPackage}{"Parameters"}="node3.html#280";
$SasIndex{"Tasks"}{"imsample"}{$SasPackage}{"Description"}="node2.html#262";

1; # This must be the last line
