# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Tasks"}{"dal"}{$SasPackage}{"Description"}="node3.html#317";
$SasIndex{"Parameters"}{"showdaltrace"}{$SasPackage}{"Parameters"}="node5.html#350";
$SasIndex{"Parameters"}{"showhistory"}{$SasPackage}{"Parameters"}="node5.html#357";
$SasIndex{"Parameters"}{"scriptfile"}{$SasPackage}{"Parameters"}="node5.html#371";
$SasIndex{"Parameters"}{"withscriptfile"}{$SasPackage}{"Parameters"}="node5.html#364";
$SasIndex{"Parameters"}{"sets"}{$SasPackage}{"Parameters"}="node5.html#343";
$SasIndex{"Tasks"}{"playback"}{$SasPackage}{"Description"}="node3.html#325";

1; # This must be the last line
