# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Columns"}{"PHASE"}{$SasPackage}{"Description"}="node3.html#346";
$SasIndex{"Parameters"}{"frequencydot"}{$SasPackage}{"Parameters"}="node5.html#386";
$SasIndex{"Attributes"}{"TIMEZERO"}{$SasPackage}{"Description"}="node3.html#356";
$SasIndex{"Tasks"}{"tabcalc"}{$SasPackage}{"Comments"}="node10.html#468";
$SasIndex{"Tasks"}{"evselect"}{$SasPackage}{"Comments"}="node10.html#456";
$SasIndex{"Columns"}{"TIME"}{$SasPackage}{"Description"}="node3.html#352";
$SasIndex{"Errors"}{"PhaseColumnExists"}{$SasPackage}{"Errors"}="node6.html#435";
$SasIndex{"Tasks"}{"phasecalc"}{$SasPackage}{"Description"}="node3.html#342";
$SasIndex{"Attributes"}{"TIMESYS"}{$SasPackage}{"Description"}="node3.html#366";
$SasIndex{"Attributes"}{"MJDREF"}{$SasPackage}{"Description"}="node3.html#354";
$SasIndex{"Parameters"}{"phase"}{$SasPackage}{"Parameters"}="node5.html#400";
$SasIndex{"Errors"}{"MjdrefDoesNotExist"}{$SasPackage}{"Errors"}="node6.html#419";
$SasIndex{"Tasks"}{"xmmselect"}{$SasPackage}{"Comments"}="node10.html#460";
$SasIndex{"Errors"}{"TimezeroDoesNotExist"}{$SasPackage}{"Errors"}="node6.html#411";
$SasIndex{"Parameters"}{"frequency"}{$SasPackage}{"Parameters"}="node5.html#379";
$SasIndex{"Warnings"}{"SubProcessError"}{$SasPackage}{"Errors"}="node6.html#443";
$SasIndex{"Parameters"}{"tables"}{$SasPackage}{"Parameters"}="node5.html#372";
$SasIndex{"Errors"}{"TimeColumnDoesNotExist"}{$SasPackage}{"Errors"}="node6.html#427";
$SasIndex{"Parameters"}{"epoch"}{$SasPackage}{"Parameters"}="node5.html#393";

1; # This must be the last line
