# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Attributes"}{"CCDID"}{$SasPackage}{"Errors"}="node38.html#488";
$SasIndex{"Columns"}{"PERIPIX"}{$SasPackage}{"energy combination"}="node34.html#455";
$SasIndex{"Warnings"}{"getCcd13"}{$SasPackage}{"Errors"}="node38.html#513";
$SasIndex{"Warnings"}{"getCcd18"}{$SasPackage}{"Errors"}="node38.html#565";
$SasIndex{"Warnings"}{"equalKeywords13"}{$SasPackage}{"Errors"}="node38.html#586";
$SasIndex{"Attributes"}{"CCDNODE"}{$SasPackage}{"Errors"}="node38.html#507";
$SasIndex{"Columns"}{"PHA"}{$SasPackage}{"energy combination"}="node34.html#453";
$SasIndex{"Warnings"}{"equalKeywords14"}{$SasPackage}{"Errors"}="node38.html#591";
$SasIndex{"Attributes"}{"INSTRUME"}{$SasPackage}{"Errors"}="node38.html#496";
$SasIndex{"Warnings"}{"getCcd11"}{$SasPackage}{"Errors"}="node38.html#494";
$SasIndex{"Warnings"}{"getCcd16"}{$SasPackage}{"Errors"}="node38.html#546";
$SasIndex{"Warnings"}{"getCcd15"}{$SasPackage}{"Errors"}="node38.html#535";
$SasIndex{"Attributes"}{"QUADRANT"}{$SasPackage}{"Errors"}="node38.html#540";
$SasIndex{"Warnings"}{"equalKeywords12"}{$SasPackage}{"Errors"}="node38.html#581";
$SasIndex{"Errors"}{"getMode01"}{$SasPackage}{"Errors"}="node38.html#465";
$SasIndex{"Errors"}{"readBadpix01"}{$SasPackage}{"Errors"}="node38.html#481";
$SasIndex{"Warnings"}{"getCcd17"}{$SasPackage}{"Errors"}="node38.html#554";
$SasIndex{"Warnings"}{"getCcd10"}{$SasPackage}{"Errors"}="node38.html#486";
$SasIndex{"Attributes"}{"DATATYPE"}{$SasPackage}{"Errors"}="node38.html#467";
$SasIndex{"Warnings"}{"putPrimaryKeywords10"}{$SasPackage}{"Errors"}="node38.html#601";
$SasIndex{"Warnings"}{"equalKeywords15"}{$SasPackage}{"Errors"}="node38.html#596";
$SasIndex{"Errors"}{"getMode02"}{$SasPackage}{"Errors"}="node38.html#473";
$SasIndex{"Tasks"}{"emenergy"}{$SasPackage}{"energy combination"}="node34.html#457";
$SasIndex{"Warnings"}{"getCcd12"}{$SasPackage}{"Errors"}="node38.html#502";
$SasIndex{"Warnings"}{"sizeListParam10"}{$SasPackage}{"Errors"}="node38.html#606";
$SasIndex{"Warnings"}{"equalKeywords11"}{$SasPackage}{"Errors"}="node38.html#576";
$SasIndex{"Warnings"}{"getCcd14"}{$SasPackage}{"Errors"}="node38.html#524";
$SasIndex{"Warnings"}{"readListParam10"}{$SasPackage}{"Errors"}="node38.html#611";

1; # This must be the last line
