# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"specfile"}{$SasPackage}{"Parameters"}="node4.html#324";
$SasIndex{"Parameters"}{"mode"}{$SasPackage}{"Parameters"}="node4.html#297";
$SasIndex{"Parameters"}{"maskfile"}{$SasPackage}{"Parameters"}="node4.html#314";
$SasIndex{"Parameters"}{"spfile"}{$SasPackage}{"Parameters"}="node4.html#331";
$SasIndex{"Parameters"}{"caldb"}{$SasPackage}{"Parameters"}="node4.html#290";
$SasIndex{"Parameters"}{"det"}{$SasPackage}{"Parameters"}="node4.html#304";

1; # This must be the last line
