# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Tasks"}{"attmove"}{$SasPackage}{"Description"}="node3.html#332";
$SasIndex{"Columns"}{"DEC"}{$SasPackage}{"Input Files"}="node6.html#427";
$SasIndex{"Parameters"}{"refdec"}{$SasPackage}{"Parameters"}="node4.html#397";
$SasIndex{"Errors"}{"invalidArgs"}{$SasPackage}{"Errors"}="node5.html#422";
$SasIndex{"Columns"}{"RA"}{$SasPackage}{"Input Files"}="node6.html#425";
$SasIndex{"Parameters"}{"creatediagnostics"}{$SasPackage}{"Parameters"}="node4.html#404";
$SasIndex{"Columns"}{"DELTA"}{$SasPackage}{"Input Files"}="node6.html#429";
$SasIndex{"Parameters"}{"minstable"}{$SasPackage}{"Parameters"}="node4.html#369";
$SasIndex{"Columns"}{"MJD"}{$SasPackage}{"Input Files"}="node6.html#423";
$SasIndex{"Tasks"}{"movecalc"}{$SasPackage}{"Description"}="node3.html#336";
$SasIndex{"Parameters"}{"granularity"}{$SasPackage}{"Parameters"}="node4.html#376";
$SasIndex{"Parameters"}{"input"}{$SasPackage}{"Parameters"}="node4.html#348";
$SasIndex{"Parameters"}{"refra"}{$SasPackage}{"Parameters"}="node4.html#390";
$SasIndex{"Parameters"}{"withrefatt"}{$SasPackage}{"Parameters"}="node4.html#383";
$SasIndex{"Parameters"}{"diagfile"}{$SasPackage}{"Parameters"}="node4.html#411";
$SasIndex{"Parameters"}{"output"}{$SasPackage}{"Parameters"}="node4.html#355";
$SasIndex{"Parameters"}{"track"}{$SasPackage}{"Parameters"}="node4.html#362";

1; # This must be the last line
