# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"object"}{$SasPackage}{"Parameters"}="node4.html#264";
$SasIndex{"Parameters"}{"units"}{$SasPackage}{"Parameters"}="node4.html#271";

1; # This must be the last line
