# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"bkgspectrumset"}{$SasPackage}{"Parameters"}="node5.html#382";
$SasIndex{"Attributes"}{"HDUCLAS1"}{$SasPackage}{"Developer's notes"}="node12.html#496";
$SasIndex{"Warnings"}{"Already existing output file overwritten"}{$SasPackage}{"Errors"}="node6.html#469";
$SasIndex{"Tasks"}{"backcorr"}{$SasPackage}{"Description"}="node3.html#362";
$SasIndex{"Errors"}{"Invalid input file"}{$SasPackage}{"Errors"}="node6.html#429";
$SasIndex{"Errors"}{"No valid data points to plot"}{$SasPackage}{"Errors"}="node6.html#444";
$SasIndex{"Errors"}{"Energy bin width negative"}{$SasPackage}{"Errors"}="node6.html#449";
$SasIndex{"Errors"}{"Incorrect spectrum extension"}{$SasPackage}{"Errors"}="node6.html#439";
$SasIndex{"Tasks"}{"especplot"}{$SasPackage}{"Home Page"}="especplot.html#342";
$SasIndex{"Attributes"}{"INSTRUMENT"}{$SasPackage}{"Developer's notes"}="node12.html#492";
$SasIndex{"Errors"}{"Invalid output file"}{$SasPackage}{"Errors"}="node6.html#434";
$SasIndex{"Warnings"}{"Invalid binning size"}{$SasPackage}{"Errors"}="node6.html#464";
$SasIndex{"Errors"}{"Existing file cannot be overwritten"}{$SasPackage}{"Errors"}="node6.html#459";
$SasIndex{"Errors"}{"Device not supported"}{$SasPackage}{"Errors"}="node6.html#454";
$SasIndex{"Parameters"}{"binsize"}{$SasPackage}{"Parameters"}="node5.html#399";
$SasIndex{"Attributes"}{"CHANTYPE"}{$SasPackage}{"Developer's notes"}="node12.html#502";
$SasIndex{"Attributes"}{"HDUCLAS2"}{$SasPackage}{"Developer's notes"}="node12.html#498";
$SasIndex{"Errors"}{"Parameters missing"}{$SasPackage}{"Errors"}="node6.html#424";
$SasIndex{"Parameters"}{"plotfile"}{$SasPackage}{"Parameters"}="node5.html#413";
$SasIndex{"Tasks"}{"evselect"}{$SasPackage}{"Description"}="node3.html#350";
$SasIndex{"Attributes"}{"HDUCLASS"}{$SasPackage}{"Developer's notes"}="node12.html#494";
$SasIndex{"Parameters"}{"withbinning"}{$SasPackage}{"Parameters"}="node5.html#392";
$SasIndex{"Attributes"}{"HDUCLAS3"}{$SasPackage}{"Developer's notes"}="node12.html#500";
$SasIndex{"Parameters"}{"srcspectrumset"}{$SasPackage}{"Parameters"}="node5.html#372";
$SasIndex{"Parameters"}{"plotdevice"}{$SasPackage}{"Parameters"}="node5.html#406";

1; # This must be the last line
