# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"oldsumset"}{$SasPackage}{"Parameters"}="node4.html#386";
$SasIndex{"Columns"}{"SPEC_NUM"}{$SasPackage}{"Description"}="node3.html#326";
$SasIndex{"Columns"}{"GROUPING"}{$SasPackage}{"Description"}="node3.html#342";
$SasIndex{"Errors"}{"NotMultipleSpecFile"}{$SasPackage}{"Errors"}="node5.html#418";
$SasIndex{"Columns"}{"CORRSCAL"}{$SasPackage}{"Description"}="node3.html#350";
$SasIndex{"Columns"}{"QUALITY"}{$SasPackage}{"Description"}="node3.html#340";
$SasIndex{"Tasks"}{"specadd"}{$SasPackage}{"Description"}="node3.html#320";
$SasIndex{"Parameters"}{"useoldsumset"}{$SasPackage}{"Parameters"}="node4.html#379";
$SasIndex{"Parameters"}{"sets"}{$SasPackage}{"Parameters"}="node4.html#372";
$SasIndex{"Columns"}{"BACKSCAL"}{$SasPackage}{"Description"}="node3.html#346";
$SasIndex{"Columns"}{"ROWID"}{$SasPackage}{"Description"}="node3.html#338";
$SasIndex{"Parameters"}{"sumset"}{$SasPackage}{"Parameters"}="node4.html#393";
$SasIndex{"Columns"}{"BACKFILE"}{$SasPackage}{"Description"}="node3.html#344";
$SasIndex{"Columns"}{"CORRFILE"}{$SasPackage}{"Description"}="node3.html#348";
$SasIndex{"Errors"}{"NotSingleSpecFile"}{$SasPackage}{"Errors"}="node5.html#411";
$SasIndex{"Columns"}{"COUNTS"}{$SasPackage}{"Description"}="node3.html#330";
$SasIndex{"Errors"}{"NotSpecFile"}{$SasPackage}{"Errors"}="node5.html#404";
$SasIndex{"Attributes"}{"POISSERR"}{$SasPackage}{"Description"}="node3.html#360";
$SasIndex{"Columns"}{"STAT_ERR"}{$SasPackage}{"Description"}="node3.html#334";
$SasIndex{"Warnings"}{"NoExposure"}{$SasPackage}{"Errors"}="node5.html#425";
$SasIndex{"Columns"}{"RESPFILE"}{$SasPackage}{"Description"}="node3.html#352";
$SasIndex{"Columns"}{"CHANNEL"}{$SasPackage}{"Description"}="node3.html#328";
$SasIndex{"Columns"}{"ANCRFILE"}{$SasPackage}{"Description"}="node3.html#354";
$SasIndex{"Attributes"}{"EXPOSURE"}{$SasPackage}{"Errors"}="node5.html#427";

1; # This must be the last line
