# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"outset"}{$SasPackage}{"Parameters"}="node4.html#338";
$SasIndex{"Parameters"}{"nphset"}{$SasPackage}{"Parameters"}="node4.html#317";
$SasIndex{"Errors"}{"Y Image size computed from BINPE, WINDOWDY and BINAX2 does not equal NAXIS2"}{$SasPackage}{"Errors"}="node5.html#388";
$SasIndex{"Errors"}{"Bad File Type"}{$SasPackage}{"Errors"}="node5.html#363";
$SasIndex{"Parameters"}{"modeset"}{$SasPackage}{"Parameters"}="node4.html#345";
$SasIndex{"Errors"}{"Wrong Mode"}{$SasPackage}{"Errors"}="node5.html#368";
$SasIndex{"Warnings"}{"(N) Negative pixel values encountered"}{$SasPackage}{"Errors"}="node5.html#393";
$SasIndex{"Parameters"}{"rawattitude"}{$SasPackage}{"Parameters"}="node4.html#352";
$SasIndex{"Errors"}{"Invalid filter string"}{$SasPackage}{"Errors"}="node5.html#373";
$SasIndex{"Parameters"}{"set"}{$SasPackage}{"Parameters"}="node4.html#310";
$SasIndex{"Errors"}{"X Image size computed from BINPE, WINDOWDX and BINAX1 does not equal NAXIS1"}{$SasPackage}{"Errors"}="node5.html#383";
$SasIndex{"Warnings"}{"Exposure time is zero- calculating it from the summary file"}{$SasPackage}{"Errors"}="node5.html#403";
$SasIndex{"Warnings"}{"ZERODRIFT"}{$SasPackage}{"Errors"}="node5.html#398";
$SasIndex{"Errors"}{"getstartendexp_mod"}{$SasPackage}{"Errors"}="node5.html#378";
$SasIndex{"Parameters"}{"pehset"}{$SasPackage}{"Parameters"}="node4.html#324";
$SasIndex{"Parameters"}{"wdxset"}{$SasPackage}{"Parameters"}="node4.html#331";

1; # This must be the last line
