# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"caldb"}{$SasPackage}{"Parameters"}="node4.html#324";
$SasIndex{"Parameters"}{"clobber"}{$SasPackage}{"Parameters"}="node4.html#359";
$SasIndex{"Parameters"}{"quad[1-4]"}{$SasPackage}{"Parameters"}="node4.html#352";
$SasIndex{"Parameters"}{"ehigh"}{$SasPackage}{"Parameters"}="node4.html#345";
$SasIndex{"Parameters"}{"elow"}{$SasPackage}{"Parameters"}="node4.html#338";
$SasIndex{"Parameters"}{"diag"}{$SasPackage}{"Parameters"}="node4.html#331";
$SasIndex{"Parameters"}{"prefix"}{$SasPackage}{"Parameters"}="node4.html#317";

1; # This must be the last line
