# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"nbins"}{$SasPackage}{"Parameters"}="node5.html#529";
$SasIndex{"Warnings"}{"rebintype is positive but not an integer"}{$SasPackage}{"Errors"}="node6.html#707";
$SasIndex{"Parameters"}{"normalization"}{$SasPackage}{"Parameters"}="node5.html#561";
$SasIndex{"Errors"}{"Device not recognized"}{$SasPackage}{"Errors"}="node6.html#672";
$SasIndex{"Parameters"}{"xscale"}{$SasPackage}{"Parameters"}="node5.html#637";
$SasIndex{"Parameters"}{"gtiset"}{$SasPackage}{"Parameters"}="node5.html#658";
$SasIndex{"Parameters"}{"rebin"}{$SasPackage}{"Parameters"}="node5.html#609";
$SasIndex{"Parameters"}{"polyorder"}{$SasPackage}{"Parameters"}="node5.html#593";
$SasIndex{"Warnings"}{"NoGTIs"}{$SasPackage}{"Errors"}="node6.html#687";
$SasIndex{"Errors"}{"GTI file does not exist"}{$SasPackage}{"Errors"}="node6.html#682";
$SasIndex{"Attributes"}{"TIMEDEL"}{$SasPackage}{"Description"}="node3.html#478";
$SasIndex{"Parameters"}{"plotdevice"}{$SasPackage}{"Parameters"}="node5.html#623";
$SasIndex{"Parameters"}{"npoints"}{$SasPackage}{"Parameters"}="node5.html#575";
$SasIndex{"Parameters"}{"operation"}{$SasPackage}{"Parameters"}="node5.html#602";
$SasIndex{"Tasks"}{"elcbuild"}{$SasPackage}{"Input Files"}="node7.html#720";
$SasIndex{"Parameters"}{"outfile"}{$SasPackage}{"Parameters"}="node5.html#630";
$SasIndex{"Parameters"}{"infile"}{$SasPackage}{"Parameters"}="node5.html#519";
$SasIndex{"Warnings"}{"NotEnoughBins"}{$SasPackage}{"Errors"}="node6.html#692";
$SasIndex{"Warnings"}{"Some header keywords are missing or inconsistent"}{$SasPackage}{"Errors"}="node6.html#717";
$SasIndex{"Parameters"}{"rebintype"}{$SasPackage}{"Parameters"}="node5.html#616";
$SasIndex{"Attributes"}{"RATE"}{$SasPackage}{"Description"}="node3.html#474";
$SasIndex{"Tasks"}{"efftplot"}{$SasPackage}{"Home Page"}="efftplot.html#440";
$SasIndex{"Parameters"}{"nerrorpoints"}{$SasPackage}{"Parameters"}="node5.html#551";
$SasIndex{"Parameters"}{"fillgaps"}{$SasPackage}{"Parameters"}="node5.html#568";
$SasIndex{"Errors"}{"Output file cannot be overwritten"}{$SasPackage}{"Errors"}="node6.html#677";
$SasIndex{"Parameters"}{"gtis"}{$SasPackage}{"Parameters"}="node5.html#651";
$SasIndex{"Tasks"}{"tabgtigen"}{$SasPackage}{"Description"}="node3.html#480";
$SasIndex{"Warnings"}{"rebintype is negative and outside the allowed range."}{$SasPackage}{"Errors"}="node6.html#712";
$SasIndex{"Parameters"}{"removetrend"}{$SasPackage}{"Parameters"}="node5.html#586";
$SasIndex{"Parameters"}{"yscale"}{$SasPackage}{"Parameters"}="node5.html#644";
$SasIndex{"Warnings"}{"Unavailable device type and/or output file"}{$SasPackage}{"Errors"}="node6.html#697";
$SasIndex{"Warnings"}{"nbins must be a power of two lower than NBINLC (the number of bins in the light curve)"}{$SasPackage}{"Errors"}="node6.html#702";
$SasIndex{"Parameters"}{"bkgsub"}{$SasPackage}{"Parameters"}="node5.html#544";

1; # This must be the last line
