# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Tasks"}{"param"}{$SasPackage}{"Concept"}="node2.html#218";
$SasIndex{"Environments"}{"SAS_PATH"}{$SasPackage}{"Usage"}="node3.html#223";
$SasIndex{"Environments"}{"SAS_DIR"}{$SasPackage}{"Usage"}="node3.html#225";

1; # This must be the last line
