# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Tasks"}{"rgsrmfgen"}{$SasPackage}{"Description"}="node3.html#272";
$SasIndex{"Columns"}{"PI"}{$SasPackage}{"Input Files"}="node6.html#286";
$SasIndex{"Columns"}{"BETA_CHANNEL"}{$SasPackage}{"Input Files"}="node6.html#288";
$SasIndex{"Blocks"}{"EVENTS"}{$SasPackage}{"Input Files"}="node6.html#284";
$SasIndex{"Parameters"}{"set"}{$SasPackage}{"Parameters"}="node4.html#276";
$SasIndex{"Tasks"}{"rgsregions"}{$SasPackage}{"Description"}="node3.html#264";
$SasIndex{"Tasks"}{"rgsspectrum"}{$SasPackage}{"Description"}="node3.html#268";
$SasIndex{"Columns"}{"XDSP_CHANNEL"}{$SasPackage}{"Input Files"}="node6.html#290";

1; # This must be the last line
