# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"ehighlist"}{$SasPackage}{"Parameters"}="node4.html#391";
$SasIndex{"Parameters"}{"clobber"}{$SasPackage}{"Parameters"}="node4.html#420";
$SasIndex{"Parameters"}{"alpha"}{$SasPackage}{"Parameters"}="node4.html#377";
$SasIndex{"Parameters"}{"caldb"}{$SasPackage}{"Parameters"}="node4.html#349";
$SasIndex{"Parameters"}{"prefixlist"}{$SasPackage}{"Parameters"}="node4.html#413";
$SasIndex{"Parameters"}{"mask"}{$SasPackage}{"Parameters"}="node4.html#398";
$SasIndex{"Parameters"}{"elowlist"}{$SasPackage}{"Parameters"}="node4.html#384";
$SasIndex{"Parameters"}{"withsoftcontrol"}{$SasPackage}{"Parameters"}="node4.html#363";
$SasIndex{"Parameters"}{"withswcxcontrol"}{$SasPackage}{"Parameters"}="node4.html#370";
$SasIndex{"Parameters"}{"withpartcontrol"}{$SasPackage}{"Parameters"}="node4.html#356";

1; # This must be the last line
