# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Errors"}{"twomassRead"}{$SasPackage}{"Errors"}="node6.html#314";
$SasIndex{"Errors"}{"twomassSearch"}{$SasPackage}{"Errors"}="node6.html#329";
$SasIndex{"Errors"}{"fitsioError"}{$SasPackage}{"Errors"}="node6.html#354";
$SasIndex{"Errors"}{"usnoSearch"}{$SasPackage}{"Errors"}="node6.html#349";
$SasIndex{"Errors"}{"twomassRecord"}{$SasPackage}{"Errors"}="node6.html#319";
$SasIndex{"Errors"}{"usnoSize"}{$SasPackage}{"Errors"}="node6.html#344";
$SasIndex{"Errors"}{"usnoRecord"}{$SasPackage}{"Errors"}="node6.html#339";
$SasIndex{"Errors"}{"missingKeyword"}{$SasPackage}{"Errors"}="node6.html#304";
$SasIndex{"Parameters"}{"catextract"}{$SasPackage}{"Parameters"}="node5.html#293";
$SasIndex{"Errors"}{"usnoRead"}{$SasPackage}{"Errors"}="node6.html#334";
$SasIndex{"Parameters"}{"srclistset"}{$SasPackage}{"Parameters"}="node5.html#286";
$SasIndex{"Errors"}{"twomassSize"}{$SasPackage}{"Errors"}="node6.html#324";
$SasIndex{"Errors"}{"catWriteExtracts"}{$SasPackage}{"Errors"}="node6.html#309";

1; # This must be the last line
