# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"dir"}{$SasPackage}{"Parameters"}="node4.html#283";
$SasIndex{"Parameters"}{"column"}{$SasPackage}{"Parameters"}="node4.html#269";
$SasIndex{"Parameters"}{"newcolumn"}{$SasPackage}{"Parameters"}="node4.html#290";
$SasIndex{"Parameters"}{"type"}{$SasPackage}{"Parameters"}="node4.html#276";

1; # This must be the last line
