# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"expression"}{$SasPackage}{"Parameters"}="node3.html#303";
$SasIndex{"Tasks"}{"selectlib"}{$SasPackage}{"Description"}="node2.html#271";
$SasIndex{"Parameters"}{"tempimageset"}{$SasPackage}{"Parameters"}="node3.html#296";
$SasIndex{"Parameters"}{"imageset"}{$SasPackage}{"Parameters"}="node3.html#275";
$SasIndex{"Parameters"}{"tempset"}{$SasPackage}{"Parameters"}="node3.html#289";
$SasIndex{"Tasks"}{"immask"}{$SasPackage}{"Description"}="node2.html#266";
$SasIndex{"Parameters"}{"maskset"}{$SasPackage}{"Parameters"}="node3.html#282";
$SasIndex{"Errors"}{"badArrayDataType"}{$SasPackage}{"Errors"}="node4.html#314";

1; # This must be the last line
