# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Warnings"}{"Input background rates table is empty"}{$SasPackage}{"Errors"}="node5.html#437";
$SasIndex{"Warnings"}{"Background subtracted rate has negative values"}{$SasPackage}{"Errors"}="node5.html#457";
$SasIndex{"Parameters"}{"srcregionset"}{$SasPackage}{"Parameters"}="node4.html#354";
$SasIndex{"Parameters"}{"imageset"}{$SasPackage}{"Parameters"}="node4.html#407";
$SasIndex{"Warnings"}{"Wrong number of bins in the light curve table length"}{$SasPackage}{"Errors"}="node5.html#467";
$SasIndex{"Warnings"}{"High value of the source rate"}{$SasPackage}{"Errors"}="node5.html#452";
$SasIndex{"Parameters"}{"wdxset"}{$SasPackage}{"Parameters"}="node4.html#386";
$SasIndex{"Warnings"}{"Background rates and region files have different EXP_IDs"}{$SasPackage}{"Errors"}="node5.html#447";
$SasIndex{"Parameters"}{"subtractbkg"}{$SasPackage}{"Parameters"}="node4.html#421";
$SasIndex{"Parameters"}{"outset"}{$SasPackage}{"Parameters"}="node4.html#393";
$SasIndex{"Parameters"}{"mod8corrupted"}{$SasPackage}{"Parameters"}="node4.html#400";
$SasIndex{"Warnings"}{"Block RATE does not exist in the background rates file"}{$SasPackage}{"Errors"}="node5.html#432";
$SasIndex{"Warnings"}{"Block RATE does not exist in the source rates file"}{$SasPackage}{"Errors"}="node5.html#462";
$SasIndex{"Parameters"}{"bkgfromimage"}{$SasPackage}{"Parameters"}="node4.html#414";
$SasIndex{"Warnings"}{"Source and background rates files from different exposures"}{$SasPackage}{"Errors"}="node5.html#442";
$SasIndex{"Parameters"}{"srcrateset"}{$SasPackage}{"Parameters"}="node4.html#346";
$SasIndex{"Errors"}{"Impossible to get correct source rates table length"}{$SasPackage}{"Errors"}="node5.html#472";
$SasIndex{"Parameters"}{"bkgregionset"}{$SasPackage}{"Parameters"}="node4.html#370";
$SasIndex{"Parameters"}{"sourcelistset"}{$SasPackage}{"Parameters"}="node4.html#378";
$SasIndex{"Parameters"}{"bkdrateset"}{$SasPackage}{"Parameters"}="node4.html#362";

1; # This must be the last line
