# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"outset"}{$SasPackage}{"Parameters"}="node4.html#778";
$SasIndex{"Errors"}{"<"}{$SasPackage}{"Errors"}="node6.html#882";
$SasIndex{"Parameters"}{"maxrawcountrate"}{$SasPackage}{"Parameters"}="node4.html#859";
$SasIndex{"Parameters"}{"regionfile"}{$SasPackage}{"Parameters"}="node4.html#821";
$SasIndex{"Parameters"}{"backgroundmethod"}{$SasPackage}{"Parameters"}="node4.html#866";
$SasIndex{"Parameters"}{"levelimage"}{$SasPackage}{"Parameters"}="node4.html#807";
$SasIndex{"Errors"}{"WrongFilter"}{$SasPackage}{"Errors"}="node6.html#900";
$SasIndex{"Warnings"}{"Failed to release memory for: <I>name</I> "}{$SasPackage}{"Errors"}="node6.html#912";
$SasIndex{"Parameters"}{"neighboursforpsfphotometry"}{$SasPackage}{"Parameters"}="node4.html#842";
$SasIndex{"Parameters"}{"psfphotometryenabled"}{$SasPackage}{"Parameters"}="node4.html#835";
$SasIndex{"Parameters"}{"set"}{$SasPackage}{"Parameters"}="node4.html#769";
$SasIndex{"Errors"}{"image file is not 2D"}{$SasPackage}{"Errors"}="node6.html#877";
$SasIndex{"Parameters"}{"wdxset"}{$SasPackage}{"Parameters"}="node4.html#785";
$SasIndex{"Parameters"}{"nsigma"}{$SasPackage}{"Parameters"}="node4.html#792";
$SasIndex{"Parameters"}{"psfphotometryset"}{$SasPackage}{"Parameters"}="node4.html#852";
$SasIndex{"Parameters"}{"minsignificance"}{$SasPackage}{"Parameters"}="node4.html#799";
$SasIndex{"Parameters"}{"detectextended"}{$SasPackage}{"Parameters"}="node4.html#828";
$SasIndex{"Errors"}{"Could not allocate memory for: <I>name</I> "}{$SasPackage}{"Errors"}="node6.html#894";
$SasIndex{"Parameters"}{"backgroundimage"}{$SasPackage}{"Parameters"}="node4.html#814";

1; # This must be the last line
