# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"calindex1set"}{$SasPackage}{"Parameters"}="node4.html#279";
$SasIndex{"Tasks"}{"cifdiff"}{$SasPackage}{"Description"}="node3.html#275";
$SasIndex{"Tasks"}{"cifbuild"}{$SasPackage}{"Input Files"}="node6.html#307";
$SasIndex{"Parameters"}{"withfile"}{$SasPackage}{"Parameters"}="node4.html#293";
$SasIndex{"Parameters"}{"outfile"}{$SasPackage}{"Parameters"}="node4.html#300";
$SasIndex{"Parameters"}{"calindex2set"}{$SasPackage}{"Parameters"}="node4.html#286";

1; # This must be the last line
