# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Errors"}{"WriteError"}{$SasPackage}{"Errors"}="node5.html#304";
$SasIndex{"Parameters"}{"responsefile"}{$SasPackage}{"Parameters"}="node4.html#293";
$SasIndex{"Tasks"}{"omgchain"}{$SasPackage}{"Description"}="node3.html#275";
$SasIndex{"Parameters"}{"outputspec"}{$SasPackage}{"Parameters"}="node4.html#286";
$SasIndex{"Parameters"}{"inputspec"}{$SasPackage}{"Parameters"}="node4.html#279";

1; # This must be the last line
