# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Errors"}{"badFileMode"}{$SasPackage}{"Errors"}="node5.html#315";
$SasIndex{"Parameters"}{"nphset"}{$SasPackage}{"Parameters"}="node4.html#290";
$SasIndex{"Parameters"}{"thxset"}{$SasPackage}{"Parameters"}="node4.html#283";
$SasIndex{"Parameters"}{"modeset"}{$SasPackage}{"Parameters"}="node4.html#304";
$SasIndex{"Warnings"}{"ZERODRFIT"}{$SasPackage}{"Errors"}="node5.html#320";
$SasIndex{"Parameters"}{"outset"}{$SasPackage}{"Parameters"}="node4.html#297";

1; # This must be the last line
