# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"sets"}{$SasPackage}{"Parameters"}="node4.html#296";
$SasIndex{"Parameters"}{"calindexset"}{$SasPackage}{"Parameters"}="node4.html#289";
$SasIndex{"Tasks"}{"cifremove"}{$SasPackage}{"Description"}="node3.html#285";
$SasIndex{"Tasks"}{"cifbuild"}{$SasPackage}{"Description"}="node3.html#276";
$SasIndex{"Tasks"}{"cifinsert"}{$SasPackage}{"Description"}="node3.html#272";

1; # This must be the last line
