# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Errors"}{"Bad File Type"}{$SasPackage}{"Errors"}="node5.html#301";
$SasIndex{"Parameters"}{"set"}{$SasPackage}{"Parameters"}="node4.html#285";
$SasIndex{"Errors"}{"GetFrameTime"}{$SasPackage}{"Errors"}="node5.html#306";
$SasIndex{"Warnings"}{"Negative Count-Rate"}{$SasPackage}{"Errors"}="node5.html#296";

1; # This must be the last line
