# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"bkginner"}{$SasPackage}{"Parameters"}="node4.html#325";
$SasIndex{"Parameters"}{"srcfile"}{$SasPackage}{"Parameters"}="node4.html#346";
$SasIndex{"Parameters"}{"bkgfile"}{$SasPackage}{"Parameters"}="node4.html#353";
$SasIndex{"Parameters"}{"nfwhm"}{$SasPackage}{"Parameters"}="node4.html#339";
$SasIndex{"Parameters"}{"bkgouter"}{$SasPackage}{"Parameters"}="node4.html#332";
$SasIndex{"Parameters"}{"set"}{$SasPackage}{"Parameters"}="node4.html#304";
$SasIndex{"Parameters"}{"srcnumber"}{$SasPackage}{"Parameters"}="node4.html#311";
$SasIndex{"Errors"}{"The source number exceeds the number of sources in the OSW"}{$SasPackage}{"Errors"}="node5.html#364";
$SasIndex{"Parameters"}{"srcradius"}{$SasPackage}{"Parameters"}="node4.html#318";

1; # This must be the last line
