# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Columns"}{"CCDNR"}{$SasPackage}{"Description"}="node1.html#261";
$SasIndex{"Attributes"}{"DATE-OBS"}{$SasPackage}{"Description"}="node1.html#279";
$SasIndex{"Columns"}{"SUBMODE"}{$SasPackage}{"Description"}="node1.html#267";
$SasIndex{"Columns"}{"WINDOWX0"}{$SasPackage}{"Description"}="node1.html#269";
$SasIndex{"Tasks"}{"ssclib"}{$SasPackage}{"readCubeData"}="node3.html#281";
$SasIndex{"Columns"}{"NODE_NR"}{$SasPackage}{"Description"}="node1.html#263";
$SasIndex{"Columns"}{"WINDOWDX"}{$SasPackage}{"Description"}="node1.html#273";
$SasIndex{"Columns"}{"WINDOWDY"}{$SasPackage}{"Description"}="node1.html#275";
$SasIndex{"Tasks"}{"chipcube"}{$SasPackage}{"Home Page"}="chipcube.html#255";
$SasIndex{"Attributes"}{"INSTRUME"}{$SasPackage}{"Description"}="node1.html#277";
$SasIndex{"Blocks"}{"KEY2IMGS"}{$SasPackage}{"Description"}="node1.html#259";
$SasIndex{"Columns"}{"WINDOWY0"}{$SasPackage}{"Description"}="node1.html#271";
$SasIndex{"Columns"}{"GTI_NAME"}{$SasPackage}{"Description"}="node1.html#265";

1; # This must be the last line
