# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Tasks"}{"cal"}{$SasPackage}{"Description"}="node3.html#264";
$SasIndex{"Parameters"}{"camcoordtype"}{$SasPackage}{"Parameters"}="node4.html#280";
$SasIndex{"Parameters"}{"x"}{$SasPackage}{"Parameters"}="node4.html#293";
$SasIndex{"Parameters"}{"instrument"}{$SasPackage}{"Parameters"}="node4.html#269";
$SasIndex{"Parameters"}{"y"}{$SasPackage}{"Parameters"}="node4.html#300";

1; # This must be the last line
