# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"withcoords"}{$SasPackage}{"Parameters"}="node9.html#442";
$SasIndex{"Parameters"}{"withccd"}{$SasPackage}{"Parameters"}="node9.html#529";
$SasIndex{"Tasks"}{"selectlib"}{$SasPackage}{"Regions"}="node6.html#424";
$SasIndex{"Parameters"}{"rawx_out"}{$SasPackage}{"Parameters"}="node9.html#607";
$SasIndex{"Parameters"}{"srcexp"}{$SasPackage}{"Parameters"}="node9.html#435";
$SasIndex{"Parameters"}{"phi_out"}{$SasPackage}{"Parameters"}="node9.html#558";
$SasIndex{"Parameters"}{"rawy_out"}{$SasPackage}{"Parameters"}="node9.html#614";
$SasIndex{"Parameters"}{"ccdno"}{$SasPackage}{"Parameters"}="node9.html#544";
$SasIndex{"Parameters"}{"y"}{$SasPackage}{"Parameters"}="node9.html#466";
$SasIndex{"Parameters"}{"ra_out"}{$SasPackage}{"Parameters"}="node9.html#565";
$SasIndex{"Parameters"}{"ccd_out"}{$SasPackage}{"Parameters"}="node9.html#621";
$SasIndex{"Parameters"}{"detx_out"}{$SasPackage}{"Parameters"}="node9.html#593";
$SasIndex{"Errors"}{"noCCDNumber"}{$SasPackage}{"Errors"}="node10.html#657";
$SasIndex{"Errors"}{"InvalidExpression"}{$SasPackage}{"Errors"}="node10.html#632";
$SasIndex{"Parameters"}{"coordtype"}{$SasPackage}{"Parameters"}="node9.html#473";
$SasIndex{"Parameters"}{"dety_out"}{$SasPackage}{"Parameters"}="node9.html#600";
$SasIndex{"Parameters"}{"x"}{$SasPackage}{"Parameters"}="node9.html#459";
$SasIndex{"Warnings"}{"UnknownModeString"}{$SasPackage}{"Errors"}="node10.html#662";
$SasIndex{"Errors"}{"InvalidWCSType"}{$SasPackage}{"Errors"}="node10.html#647";
$SasIndex{"Parameters"}{"theta_out"}{$SasPackage}{"Parameters"}="node9.html#551";
$SasIndex{"Parameters"}{"posy_out"}{$SasPackage}{"Parameters"}="node9.html#586";
$SasIndex{"Warnings"}{"InvalidPosWCSInfo"}{$SasPackage}{"Errors"}="node10.html#672";
$SasIndex{"Parameters"}{"imageset"}{$SasPackage}{"Parameters"}="node9.html#428";
$SasIndex{"Parameters"}{"pos2eqpos"}{$SasPackage}{"Parameters"}="node9.html#516";
$SasIndex{"Attributes"}{"REFYCRVL"}{$SasPackage}{"Parameters"}="node9.html#507";
$SasIndex{"Parameters"}{"dec_out"}{$SasPackage}{"Parameters"}="node9.html#572";
$SasIndex{"Attributes"}{"REFXCRVL"}{$SasPackage}{"Parameters"}="node9.html#505";
$SasIndex{"Errors"}{"InvalidRegion"}{$SasPackage}{"Errors"}="node10.html#637";
$SasIndex{"Parameters"}{"posx_out"}{$SasPackage}{"Parameters"}="node9.html#579";
$SasIndex{"Warnings"}{"NoInstrument"}{$SasPackage}{"Errors"}="node10.html#667";
$SasIndex{"Errors"}{"invalidArraySize"}{$SasPackage}{"Errors"}="node10.html#642";
$SasIndex{"Errors"}{"invalidCoordType"}{$SasPackage}{"Errors"}="node10.html#652";

1; # This must be the last line
