# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"object"}{$SasPackage}{"Parameters"}="node4.html#271";
$SasIndex{"Parameters"}{"label"}{$SasPackage}{"Parameters"}="node4.html#264";

1; # This must be the last line
