# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"outset"}{$SasPackage}{"Parameters"}="node4.html#257";
$SasIndex{"Errors"}{"allocError"}{$SasPackage}{"Errors"}="node5.html#268";

1; # This must be the last line
