# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"caldb"}{$SasPackage}{"Parameters"}="node4.html#412";
$SasIndex{"Parameters"}{"ccd1-7"}{$SasPackage}{"Parameters"}="node4.html#460";
$SasIndex{"Parameters"}{"prefix"}{$SasPackage}{"Parameters"}="node4.html#405";
$SasIndex{"Parameters"}{"elow"}{$SasPackage}{"Parameters"}="node4.html#440";
$SasIndex{"Parameters"}{"mask"}{$SasPackage}{"Parameters"}="node4.html#428";
$SasIndex{"Parameters"}{"region"}{$SasPackage}{"Parameters"}="node4.html#419";
$SasIndex{"Parameters"}{"ehigh"}{$SasPackage}{"Parameters"}="node4.html#450";

1; # This must be the last line
