# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"endispset"}{$SasPackage}{"Parameters"}="node4.html#428";
$SasIndex{"Parameters"}{"paperymax"}{$SasPackage}{"Parameters"}="node4.html#541";
$SasIndex{"Parameters"}{"paperxmax"}{$SasPackage}{"Parameters"}="node4.html#534";
$SasIndex{"Parameters"}{"device"}{$SasPackage}{"Parameters"}="node4.html#492";
$SasIndex{"Errors"}{"No energy dispersion supplied "}{$SasPackage}{"Errors"}="node5.html#572";
$SasIndex{"Tasks"}{"rgsspecplot"}{$SasPackage}{"Future developments"}="node10.html#628";
$SasIndex{"Parameters"}{"invert"}{$SasPackage}{"Parameters"}="node4.html#499";
$SasIndex{"Warnings"}{"Unable to plot more than 11 fits regions in different colours"}{$SasPackage}{"Errors"}="node5.html#557";
$SasIndex{"Parameters"}{"plotfile"}{$SasPackage}{"Parameters"}="node4.html#485";
$SasIndex{"Tasks"}{"r"}{$SasPackage}{"Input Files"}="node6.html#616";
$SasIndex{"Tasks"}{"rgsregions"}{$SasPackage}{"Description"}="node3.html#398";
$SasIndex{"Parameters"}{"withspatialregionsets"}{$SasPackage}{"Parameters"}="node4.html#464";
$SasIndex{"Parameters"}{"srclistset"}{$SasPackage}{"Parameters"}="node4.html#440";
$SasIndex{"Warnings"}{"Unable to plot the coordinates of more than 3 sources"}{$SasPackage}{"Errors"}="node5.html#552";
$SasIndex{"Parameters"}{"withspatialset"}{$SasPackage}{"Parameters"}="node4.html#402";
$SasIndex{"Errors"}{"Unrecognised PGPLOT device"}{$SasPackage}{"Errors"}="node5.html#592";
$SasIndex{"Errors"}{"No spatial set supplied "}{$SasPackage}{"Errors"}="node5.html#567";
$SasIndex{"Parameters"}{"paperxmin"}{$SasPackage}{"Parameters"}="node4.html#520";
$SasIndex{"Tasks"}{"e"}{$SasPackage}{"Input Files"}="node6.html#608";
$SasIndex{"Errors"}{"No Source list provided "}{$SasPackage}{"Errors"}="node5.html#577";
$SasIndex{"Warnings"}{"Failed to delete temporary file"}{$SasPackage}{"Errors"}="node5.html#562";
$SasIndex{"Parameters"}{"withendispset"}{$SasPackage}{"Parameters"}="node4.html#421";
$SasIndex{"Parameters"}{"spatialset"}{$SasPackage}{"Parameters"}="node4.html#409";
$SasIndex{"Tasks"}{"evselect"}{$SasPackage}{"Description"}="node3.html#394";
$SasIndex{"Errors"}{"Nothing to plot"}{$SasPackage}{"Errors"}="node5.html#597";
$SasIndex{"Tasks"}{"rgsimplot"}{$SasPackage}{"Comments"}="node9.html#624";
$SasIndex{"Errors"}{"No plot file supplied "}{$SasPackage}{"Errors"}="node5.html#582";
$SasIndex{"Errors"}{"Plot file already exists"}{$SasPackage}{"Errors"}="node5.html#587";
$SasIndex{"Parameters"}{"colour"}{$SasPackage}{"Parameters"}="node4.html#513";
$SasIndex{"Parameters"}{"paperymin"}{$SasPackage}{"Parameters"}="node4.html#527";
$SasIndex{"Tasks"}{"rgssources"}{$SasPackage}{"Parameters"}="node4.html#449";
$SasIndex{"Parameters"}{"srcidlist"}{$SasPackage}{"Parameters"}="node4.html#478";
$SasIndex{"Parameters"}{"orderlist"}{$SasPackage}{"Parameters"}="node4.html#457";
$SasIndex{"Parameters"}{"colourmap"}{$SasPackage}{"Parameters"}="node4.html#506";
$SasIndex{"Parameters"}{"withendispregionsets"}{$SasPackage}{"Parameters"}="node4.html#471";
$SasIndex{"Errors"}{"Invalid graph size"}{$SasPackage}{"Errors"}="node5.html#602";

1; # This must be the last line
