# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Errors"}{"ErrIntmakehist"}{$SasPackage}{"Errors"}="node5.html#453";
$SasIndex{"Errors"}{"MissingFitsKeyw"}{$SasPackage}{"Errors"}="node5.html#464";
$SasIndex{"Parameters"}{"sets"}{$SasPackage}{"Parameters"}="node4.html#343";
$SasIndex{"Errors"}{"ErrFstruct"}{$SasPackage}{"Errors"}="node5.html#435";
$SasIndex{"Warnings"}{"EmptyHistogram"}{$SasPackage}{"Errors"}="node5.html#492";
$SasIndex{"Errors"}{"badDevice"}{$SasPackage}{"Errors"}="node5.html#459";
$SasIndex{"Errors"}{"ErrFarith"}{$SasPackage}{"Errors"}="node5.html#426";
$SasIndex{"Errors"}{"InvalidDataType"}{$SasPackage}{"Errors"}="node5.html#403";
$SasIndex{"Errors"}{"ErrFkeypar"}{$SasPackage}{"Errors"}="node5.html#444";
$SasIndex{"Errors"}{"IncNumImg"}{$SasPackage}{"Errors"}="node5.html#408";
$SasIndex{"Parameters"}{"exposuresets"}{$SasPackage}{"Parameters"}="node4.html#355";
$SasIndex{"Parameters"}{"outfile"}{$SasPackage}{"Parameters"}="node4.html#390";
$SasIndex{"Warnings"}{"NotExpMap"}{$SasPackage}{"Errors"}="node5.html#487";
$SasIndex{"Parameters"}{"tmpflatsets"}{$SasPackage}{"Parameters"}="node4.html#367";
$SasIndex{"Parameters"}{"binsize"}{$SasPackage}{"Parameters"}="node4.html#383";
$SasIndex{"Tasks"}{"inthist"}{$SasPackage}{"Algorithm"}="node8.html#493";
$SasIndex{"Errors"}{"AllocationError"}{$SasPackage}{"Errors"}="node5.html#472";
$SasIndex{"Attributes"}{"CDELT1"}{$SasPackage}{"Errors"}="node5.html#466";
$SasIndex{"Errors"}{"IncNumFlat"}{$SasPackage}{"Errors"}="node5.html#417";
$SasIndex{"Warnings"}{"NotImage"}{$SasPackage}{"Errors"}="node5.html#482";
$SasIndex{"Errors"}{"BadParamValue"}{$SasPackage}{"Errors"}="node5.html#477";

1; # This must be the last line
