# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"bkgspectrumset"}{$SasPackage}{"Parameters"}="node5.html#394";
$SasIndex{"Parameters"}{"outbkgspectrumset"}{$SasPackage}{"Parameters"}="node5.html#408";
$SasIndex{"Parameters"}{"witheventlist"}{$SasPackage}{"Parameters"}="node5.html#457";
$SasIndex{"Tasks"}{"arfgen"}{$SasPackage}{"Home Page"}="backcorr.html#354";
$SasIndex{"Parameters"}{"sourcecoords"}{$SasPackage}{"Parameters"}="node5.html#422";
$SasIndex{"Warnings"}{"Input spectrum may be wrong"}{$SasPackage}{"Errors"}="node6.html#492";
$SasIndex{"Errors"}{"Wrong instrument name"}{$SasPackage}{"Errors"}="node6.html#482";
$SasIndex{"Parameters"}{"eventlist"}{$SasPackage}{"Parameters"}="node5.html#464";
$SasIndex{"Tasks"}{"backcorr"}{$SasPackage}{"Home Page"}="backcorr.html#350";
$SasIndex{"Parameters"}{"sourcex"}{$SasPackage}{"Parameters"}="node5.html#429";
$SasIndex{"Parameters"}{"bkgdy"}{$SasPackage}{"Parameters"}="node5.html#450";
$SasIndex{"Parameters"}{"withsourceposition"}{$SasPackage}{"Parameters"}="node5.html#415";
$SasIndex{"Parameters"}{"keeparfs"}{$SasPackage}{"Parameters"}="node5.html#471";
$SasIndex{"Parameters"}{"bkgdx"}{$SasPackage}{"Parameters"}="node5.html#443";
$SasIndex{"Errors"}{"WrongSourceCoordType"}{$SasPackage}{"Errors"}="node6.html#487";
$SasIndex{"Warnings"}{"Corrected spectrum may be wrong"}{$SasPackage}{"Errors"}="node6.html#497";
$SasIndex{"Parameters"}{"srcspectrumset"}{$SasPackage}{"Parameters"}="node5.html#401";
$SasIndex{"Parameters"}{"sourcey"}{$SasPackage}{"Parameters"}="node5.html#436";

1; # This must be the last line
