# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"dirfile"}{$SasPackage}{"Parameters"}="node4.html#270";
$SasIndex{"Parameters"}{"maxlikelim"}{$SasPackage}{"Parameters"}="node4.html#283";
$SasIndex{"Parameters"}{"clobber"}{$SasPackage}{"Parameters"}="node4.html#290";

1; # This must be the last line
