# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"EventAttributes"}{"MOS_REJECTION_MASK"}{$SasPackage}{"EPIC MOS"}="node2.html#330";
$SasIndex{"EventAttributes"}{"UNKNOWN_RAWX_PATTERN"}{$SasPackage}{"Informational attributes"}="node3.html#380";
$SasIndex{"EventAttributes"}{"REJECTED_BY_GATTI"}{$SasPackage}{"EPIC MOS"}="node2.html#340";
$SasIndex{"EventAttributes"}{"ON_OFFSETCOL"}{$SasPackage}{"Informational attributes"}="node6.html#472";
$SasIndex{"EventAttributes"}{"IN_SPOILED_FRAME"}{$SasPackage}{"Informational attributes"}="node3.html#378";
$SasIndex{"EventAttributes"}{"FLICKERING"}{$SasPackage}{"EPIC MOS"}="node2.html#352";
$SasIndex{"EventAttributes"}{"DIAGONAL"}{$SasPackage}{"Informational attributes"}="node3.html#360";
$SasIndex{"EventAttributes"}{"OUT_OF_CCD_WINDOW "}{$SasPackage}{"EPIC PN"}="node5.html#448";
$SasIndex{"EventAttributes"}{"TRAILING"}{$SasPackage}{"EPIC PN"}="node5.html#444";
$SasIndex{"EventAttributes"}{"ONBOARD_SER"}{$SasPackage}{"RGS"}="node8.html#512";
$SasIndex{"EventAttributes"}{"OUT_OF_FOV"}{$SasPackage}{"Rejection attributes"}="node4.html#402";
$SasIndex{"EventAttributes"}{"ON_NODE_INTERFACE"}{$SasPackage}{"RGS"}="node8.html#506";
$SasIndex{"EventAttributes"}{"EPN_REJECTION_MASK"}{$SasPackage}{"EPIC PN"}="node5.html#432";
$SasIndex{"EventAttributes"}{"MOS_SPECTRAL_MASK"}{$SasPackage}{"EPIC MOS"}="node2.html#356";
$SasIndex{"EventAttributes"}{"CLOSE_TO_CCD_WINDOW"}{$SasPackage}{"Informational attributes"}="node3.html#364";
$SasIndex{"EventAttributes"}{"UNDERSHOOT"}{$SasPackage}{"EPIC MOS"}="node2.html#350";
$SasIndex{"EventAttributes"}{"ON_BADPIX"}{$SasPackage}{"EPIC MOS"}="node2.html#338";
$SasIndex{"EventAttributes"}{"CLOSE_TO_DEADPIX"}{$SasPackage}{"EPIC MOS"}="node2.html#358";
$SasIndex{"EventAttributes"}{"CLOSE_TO_CCD_BORDER"}{$SasPackage}{"Informational attributes"}="node3.html#362";
$SasIndex{"EventAttributes"}{"CLOSE_TO_BADROW"}{$SasPackage}{"Informational attributes"}="node3.html#376";
$SasIndex{"EventAttributes"}{"ON_WINDOW_BORDER"}{$SasPackage}{"RGS"}="node8.html#500";
$SasIndex{"EventAttributes"}{"ON_BADROW"}{$SasPackage}{"EPIC MOS"}="node2.html#346";
$SasIndex{"EventAttributes"}{"INVALID_PATTERN"}{$SasPackage}{"Informational attributes"}="node6.html#476";
$SasIndex{"EventAttributes"}{"BAD_E3E4"}{$SasPackage}{"EPIC MOS"}="node2.html#348";
$SasIndex{"EventAttributes"}{"NEXT_TO_OFFSETCOL"}{$SasPackage}{"Informational attributes"}="node6.html#470";
$SasIndex{"EventAttributes"}{"OUT_OF_CCD_WINDOW"}{$SasPackage}{"EPIC MOS"}="node2.html#342";
$SasIndex{"EventAttributes"}{"NEXT_TO_BADPIX"}{$SasPackage}{"RGS"}="node8.html#498";
$SasIndex{"EventAttributes"}{"OUTSIDE_THRESHOLDS"}{$SasPackage}{"EPIC MOS"}="node2.html#344";
$SasIndex{"EventAttributes"}{"CLOSE_TO_BADCOL"}{$SasPackage}{"Informational attributes"}="node3.html#374";
$SasIndex{"EventAttributes"}{" OUT_OF_FOV"}{$SasPackage}{"EPIC MOS"}="node2.html#332";
$SasIndex{"EventAttributes"}{"BELOW_LOWER_THRESHOLD"}{$SasPackage}{"Rejection attributes"}="node4.html#428";
$SasIndex{"EventAttributes"}{"ABOVE_UPPER_THRESHOLD,"}{$SasPackage}{"Rejection attributes"}="node4.html#430";
$SasIndex{"EventAttributes"}{"SECONDARY"}{$SasPackage}{"EPIC PN"}="node5.html#442";
$SasIndex{"EventAttributes"}{"BAD_SHAPE"}{$SasPackage}{"RGS"}="node8.html#504";
$SasIndex{"EventAttributes"}{"BELOW_ACCEPTANCE"}{$SasPackage}{"RGS"}="node8.html#502";
$SasIndex{"EventAttributes"}{"CLOSE_TO_NODE_BOUNDARY"}{$SasPackage}{"Informational attributes"}="node3.html#366";
$SasIndex{"EventAttributes"}{"ON_NODE1"}{$SasPackage}{"RGS"}="node8.html#510";
$SasIndex{"EventAttributes"}{"COSMIC_RAY"}{$SasPackage}{"EPIC MOS"}="node2.html#336";
$SasIndex{"EventAttributes"}{"IN_BAD_FRAME"}{$SasPackage}{"EPIC MOS"}="node2.html#334";
$SasIndex{"EventAttributes"}{"ON_BADOFFSET"}{$SasPackage}{"EPIC MOS"}="node2.html#354";
$SasIndex{"EventAttributes"}{"CLOSE_TO_BRIGHTPIX"}{$SasPackage}{"Informational attributes"}="node3.html#370";
$SasIndex{"EventAttributes"}{"CLOSE_TO_ONBOARD_BADPIX"}{$SasPackage}{"Informational attributes"}="node3.html#368";
$SasIndex{"EventAttributes"}{"MIP_ASSOCIATED"}{$SasPackage}{"EPIC PN"}="node5.html#446";
$SasIndex{"EventAttributes"}{"ON_NODE0"}{$SasPackage}{"RGS"}="node8.html#508";

1; # This must be the last line
