# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Attributes"}{"BACKE"}{$SasPackage}{"Errors"}="node6.html#509";
$SasIndex{"Errors"}{"Invalid input file"}{$SasPackage}{"Errors"}="node6.html#497";
$SasIndex{"Warnings"}{"Too small number of bins"}{$SasPackage}{"Errors"}="node6.html#533";
$SasIndex{"Tasks"}{"omthlcplot"}{$SasPackage}{"Description"}="node3.html#398";
$SasIndex{"Attributes"}{"TIMEDEL"}{$SasPackage}{"Description"}="node3.html#404";
$SasIndex{"Parameters"}{"binsize"}{$SasPackage}{"Parameters"}="node5.html#446";
$SasIndex{"Parameters"}{"bkgdyscale"}{$SasPackage}{"Parameters"}="node5.html#453";
$SasIndex{"Errors"}{"TestTypeUnknown"}{$SasPackage}{"Errors"}="node6.html#517";
$SasIndex{"Errors"}{"Keyword TIMEDEL missing"}{$SasPackage}{"Errors"}="node6.html#479";
$SasIndex{"Errors"}{"Unavailable default device type and/or output file"}{$SasPackage}{"Errors"}="node6.html#492";
$SasIndex{"Parameters"}{"set"}{$SasPackage}{"Parameters"}="node5.html#422";
$SasIndex{"Warnings"}{"Number of data points to plot is higher than 500"}{$SasPackage}{"Errors"}="node6.html#527";
$SasIndex{"Tasks"}{"lcplot"}{$SasPackage}{"Home Page"}="lcplot.html#364";
$SasIndex{"Attributes"}{"RATE"}{$SasPackage}{"Errors"}="node6.html#473";
$SasIndex{"Warnings"}{"Unavailable device type and/or output file"}{$SasPackage}{"Errors"}="node6.html#522";
$SasIndex{"Errors"}{"Incorrect RATE extension"}{$SasPackage}{"Errors"}="node6.html#471";
$SasIndex{"Parameters"}{"plotdevice"}{$SasPackage}{"Parameters"}="node5.html#432";
$SasIndex{"Warnings"}{"No valid data points"}{$SasPackage}{"Errors"}="node6.html#543";
$SasIndex{"Parameters"}{"tests"}{$SasPackage}{"Parameters"}="node5.html#460";
$SasIndex{"Attributes"}{"ERROR"}{$SasPackage}{"Errors"}="node6.html#505";
$SasIndex{"Errors"}{"Existing output file cannot be overwritten"}{$SasPackage}{"Errors"}="node6.html#487";
$SasIndex{"Attributes"}{"BACKV"}{$SasPackage}{"Errors"}="node6.html#507";
$SasIndex{"Tasks"}{"omlcbuild"}{$SasPackage}{"Home Page"}="lcplot.html#376";
$SasIndex{"Tasks"}{"elcbuild"}{$SasPackage}{"Home Page"}="lcplot.html#372";
$SasIndex{"Parameters"}{"plotfile"}{$SasPackage}{"Parameters"}="node5.html#439";
$SasIndex{"Attributes"}{"TSTART"}{$SasPackage}{"Description"}="node3.html#412";
$SasIndex{"Warnings"}{"Mandatory keywords are missing from the input file"}{$SasPackage}{"Errors"}="node6.html#538";

1; # This must be the last line
