# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Tasks"}{"evselect"}{$SasPackage}{"Description"}="node3.html#278";
$SasIndex{"Tasks"}{"taskmain"}{$SasPackage}{"Description"}="node3.html#282";
$SasIndex{"Errors"}{"NoHtmlDocument"}{$SasPackage}{"Errors"}="node5.html#297";
$SasIndex{"Tasks"}{"sashelp"}{$SasPackage}{"Description"}="node3.html#259";
$SasIndex{"Parameters"}{"doc"}{$SasPackage}{"Parameters"}="node4.html#286";
$SasIndex{"Environments"}{"SAS_BROWSER"}{$SasPackage}{"Description"}="node3.html#263";
$SasIndex{"Environments"}{"SAS_DIR/doc"}{$SasPackage}{"Errors"}="node5.html#299";

1; # This must be the last line
