# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"imageset"}{$SasPackage}{"Parameters"}="node13.html#416";
$SasIndex{"Parameters"}{"oldspectrumset"}{$SasPackage}{"Parameters"}="node13.html#430";
$SasIndex{"Parameters"}{"oldsrclistset"}{$SasPackage}{"Parameters"}="node13.html#423";
$SasIndex{"Parameters"}{"newspectrumset"}{$SasPackage}{"Parameters"}="node13.html#444";
$SasIndex{"Parameters"}{"newsrclistset"}{$SasPackage}{"Parameters"}="node13.html#437";
$SasIndex{"Parameters"}{"spectrumplotset"}{$SasPackage}{"Parameters"}="node13.html#451";

1; # This must be the last line
