# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"count"}{$SasPackage}{"Parameters"}="node4.html#264";
$SasIndex{"Parameters"}{"objects"}{$SasPackage}{"Parameters"}="node4.html#271";

1; # This must be the last line
