# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"withswcxcontrol"}{$SasPackage}{"Parameters"}="node4.html#380";
$SasIndex{"Parameters"}{"prefix"}{$SasPackage}{"Parameters"}="node4.html#336";
$SasIndex{"Parameters"}{"mask"}{$SasPackage}{"Parameters"}="node4.html#394";
$SasIndex{"Parameters"}{"clobber"}{$SasPackage}{"Parameters"}="node4.html#401";
$SasIndex{"Parameters"}{"withmaskcontrol"}{$SasPackage}{"Parameters"}="node4.html#387";
$SasIndex{"Parameters"}{"thresholdmasking"}{$SasPackage}{"Parameters"}="node4.html#322";
$SasIndex{"Parameters"}{"ehigh"}{$SasPackage}{"Parameters"}="node4.html#351";
$SasIndex{"Parameters"}{"binning"}{$SasPackage}{"Parameters"}="node4.html#358";
$SasIndex{"Parameters"}{"detector"}{$SasPackage}{"Parameters"}="node4.html#329";
$SasIndex{"Parameters"}{"withpartcontrol"}{$SasPackage}{"Parameters"}="node4.html#366";
$SasIndex{"Parameters"}{"elow"}{$SasPackage}{"Parameters"}="node4.html#344";
$SasIndex{"Parameters"}{"withsoftcontrol"}{$SasPackage}{"Parameters"}="node4.html#373";

1; # This must be the last line
