# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Attributes"}{"DEC_DELTA"}{$SasPackage}{"Description"}="node1.html#283";
$SasIndex{"Attributes"}{"AVRG_PNT"}{$SasPackage}{"Description"}="node1.html#279";
$SasIndex{"Attributes"}{"PA_FIRST"}{$SasPackage}{"Description"}="node1.html#265";
$SasIndex{"Attributes"}{"PA_PNT"}{$SasPackage}{"Description"}="node1.html#277";
$SasIndex{"Attributes"}{"WGTFIRST"}{$SasPackage}{"Description"}="node1.html#269";
$SasIndex{"Attributes"}{"DECFIRST"}{$SasPackage}{"Description"}="node1.html#263";
$SasIndex{"Attributes"}{"PA_DELTA"}{$SasPackage}{"Description"}="node1.html#285";
$SasIndex{"Attributes"}{"RA_DELTA"}{$SasPackage}{"Description"}="node1.html#281";
$SasIndex{"Tasks"}{"binned_att"}{$SasPackage}{"Home Page"}="binned_att.html#257";
$SasIndex{"Columns"}{"WEIGHTS"}{$SasPackage}{"Description"}="node1.html#271";
$SasIndex{"Attributes"}{"DEC_PNT"}{$SasPackage}{"Description"}="node1.html#275";
$SasIndex{"Attributes"}{"FIRST_OK"}{$SasPackage}{"Description"}="node1.html#267";
$SasIndex{"Attributes"}{"RA_PNT"}{$SasPackage}{"Description"}="node1.html#273";
$SasIndex{"Tasks"}{"attbin"}{$SasPackage}{"Description"}="node1.html#287";
$SasIndex{"Attributes"}{"RA_FIRST"}{$SasPackage}{"Description"}="node1.html#261";

1; # This must be the last line
