# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"prefixp"}{$SasPackage}{"Parameters"}="node4.html#338";
$SasIndex{"Parameters"}{"prefixm"}{$SasPackage}{"Parameters"}="node4.html#331";
$SasIndex{"Parameters"}{"verb"}{$SasPackage}{"Parameters"}="node4.html#345";
$SasIndex{"Parameters"}{"scale"}{$SasPackage}{"Parameters"}="node4.html#352";
$SasIndex{"Parameters"}{"clobber"}{$SasPackage}{"Parameters"}="node4.html#387";
$SasIndex{"Parameters"}{"ehigh"}{$SasPackage}{"Parameters"}="node4.html#380";
$SasIndex{"Parameters"}{"rate"}{$SasPackage}{"Parameters"}="node4.html#359";
$SasIndex{"Parameters"}{"dist"}{$SasPackage}{"Parameters"}="node4.html#366";
$SasIndex{"Parameters"}{"elow"}{$SasPackage}{"Parameters"}="node4.html#373";

1; # This must be the last line
