# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Errors"}{"NoEphemerisFile"}{$SasPackage}{"Errors"}="node6.html#383";
$SasIndex{"Errors"}{"NoPositionData"}{$SasPackage}{"Errors"}="node6.html#388";
$SasIndex{"Tasks"}{"heliocentriccorr"}{$SasPackage}{"Introduction"}="node4.html#302";
$SasIndex{"Parameters"}{"time"}{$SasPackage}{"Parameters"}="node5.html#353";
$SasIndex{"Parameters"}{"srclist"}{$SasPackage}{"Parameters"}="node5.html#322";
$SasIndex{"Errors"}{"ThisIsNotXMM"}{$SasPackage}{"Errors"}="node6.html#373";
$SasIndex{"Parameters"}{"ephemeris"}{$SasPackage}{"Parameters"}="node5.html#362";
$SasIndex{"Tasks"}{"heliocentricorr"}{$SasPackage}{"Introduction"}="node4.html#306";
$SasIndex{"Parameters"}{"srcra/srcdec"}{$SasPackage}{"Parameters"}="node5.html#336";
$SasIndex{"Parameters"}{"spectrumset"}{$SasPackage}{"Parameters"}="node5.html#329";
$SasIndex{"Errors"}{"SourceNotFound"}{$SasPackage}{"Errors"}="node6.html#378";

1; # This must be the last line
