# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"type"}{$SasPackage}{"Parameters"}="node4.html#293";
$SasIndex{"Parameters"}{"value"}{$SasPackage}{"Parameters"}="node4.html#307";
$SasIndex{"Parameters"}{"label"}{$SasPackage}{"Parameters"}="node4.html#279";
$SasIndex{"Parameters"}{"to"}{$SasPackage}{"Parameters"}="node4.html#286";
$SasIndex{"Parameters"}{"units"}{$SasPackage}{"Parameters"}="node4.html#300";

1; # This must be the last line
