# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"timebinsize"}{$SasPackage}{"Parameters"}="node9.html#570";
$SasIndex{"Parameters"}{"ignoremod8noise"}{$SasPackage}{"Parameters"}="node9.html#605";
$SasIndex{"Parameters"}{"contrast"}{$SasPackage}{"Parameters"}="node9.html#505";
$SasIndex{"Parameters"}{"smoothsize"}{$SasPackage}{"Parameters"}="node9.html#533";
$SasIndex{"Parameters"}{"bkginner"}{$SasPackage}{"Parameters"}="node9.html#552";
$SasIndex{"Parameters"}{"maxrawcountrate"}{$SasPackage}{"Parameters"}="node9.html#596";
$SasIndex{"Parameters"}{"boxscale"}{$SasPackage}{"Parameters"}="node9.html#496";
$SasIndex{"Parameters"}{"inpdirectory"}{$SasPackage}{"Parameters"}="node9.html#482";
$SasIndex{"Parameters"}{"outdirectory"}{$SasPackage}{"Parameters"}="node9.html#489";
$SasIndex{"Parameters"}{"nsigma"}{$SasPackage}{"Parameters"}="node9.html#523";
$SasIndex{"Parameters"}{"rawattitude"}{$SasPackage}{"Parameters"}="node9.html#621";
$SasIndex{"Parameters"}{"bkgouter"}{$SasPackage}{"Parameters"}="node9.html#561";
$SasIndex{"Parameters"}{"srcradius"}{$SasPackage}{"Parameters"}="node9.html#542";
$SasIndex{"Parameters"}{"psfphotometryenabled"}{$SasPackage}{"Parameters"}="node9.html#587";
$SasIndex{"Parameters"}{"maxscale"}{$SasPackage}{"Parameters"}="node9.html#514";
$SasIndex{"Parameters"}{"subtractbkg"}{$SasPackage}{"Parameters"}="node9.html#613";
$SasIndex{"Parameters"}{"bkgfromimage"}{$SasPackage}{"Parameters"}="node9.html#578";

1; # This must be the last line
