# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"deltadisp"}{$SasPackage}{"Parameters"}="node4.html#297";
$SasIndex{"Parameters"}{"instrument"}{$SasPackage}{"Parameters"}="node4.html#290";
$SasIndex{"Parameters"}{"ocb"}{$SasPackage}{"Parameters"}="node4.html#304";
$SasIndex{"Parameters"}{"order"}{$SasPackage}{"Parameters"}="node4.html#283";
$SasIndex{"Parameters"}{"wavelength"}{$SasPackage}{"Parameters"}="node4.html#276";

1; # This must be the last line
