# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Environments"}{"SAS_DIR"}{$SasPackage}{"Help"}="node35.html#627";
$SasIndex{"Tasks"}{"taskmain"}{$SasPackage}{"Setting preferences"}="node25.html#619";
$SasIndex{"Tasks"}{"ftools"}{$SasPackage}{"Use with FTOOLS"}="node23.html#603";
$SasIndex{"Tasks"}{"param"}{$SasPackage}{"Changing parameters"}="node13.html#597";

1; # This must be the last line
