# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"radius"}{$SasPackage}{"Parameters"}="node4.html#344";
$SasIndex{"Parameters"}{"ra"}{$SasPackage}{"Parameters"}="node4.html#323";
$SasIndex{"Parameters"}{"outputfile"}{$SasPackage}{"Parameters"}="node4.html#379";
$SasIndex{"Parameters"}{"dec"}{$SasPackage}{"Parameters"}="node4.html#330";
$SasIndex{"Parameters"}{"shape"}{$SasPackage}{"Parameters"}="node4.html#337";
$SasIndex{"Parameters"}{"semimajor"}{$SasPackage}{"Parameters"}="node4.html#351";
$SasIndex{"Parameters"}{"mode"}{$SasPackage}{"Parameters"}="node4.html#309";
$SasIndex{"Parameters"}{"detector"}{$SasPackage}{"Parameters"}="node4.html#302";
$SasIndex{"Parameters"}{"semiminor"}{$SasPackage}{"Parameters"}="node4.html#358";
$SasIndex{"Parameters"}{"imagefile"}{$SasPackage}{"Parameters"}="node4.html#316";
$SasIndex{"Parameters"}{"inputfile"}{$SasPackage}{"Parameters"}="node4.html#372";
$SasIndex{"Parameters"}{"rotangle"}{$SasPackage}{"Parameters"}="node4.html#365";

1; # This must be the last line
