# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"specname"}{$SasPackage}{"Parameters"}="node4.html#349";
$SasIndex{"Parameters"}{"bnorm"}{$SasPackage}{"Parameters"}="node4.html#419";
$SasIndex{"Parameters"}{"bbreak"}{$SasPackage}{"Parameters"}="node4.html#405";
$SasIndex{"Parameters"}{"spectrumcontrol"}{$SasPackage}{"Parameters"}="node4.html#377";
$SasIndex{"Parameters"}{"pnorm"}{$SasPackage}{"Parameters"}="node4.html#391";
$SasIndex{"Parameters"}{"ccd[1-7]"}{$SasPackage}{"Parameters"}="node4.html#356";
$SasIndex{"Parameters"}{"prefix"}{$SasPackage}{"Parameters"}="node4.html#335";
$SasIndex{"Parameters"}{"ehigh"}{$SasPackage}{"Parameters"}="node4.html#370";
$SasIndex{"Parameters"}{"bindh"}{$SasPackage}{"Parameters"}="node4.html#412";
$SasIndex{"Parameters"}{"caldb"}{$SasPackage}{"Parameters"}="node4.html#342";
$SasIndex{"Parameters"}{"pindex"}{$SasPackage}{"Parameters"}="node4.html#384";
$SasIndex{"Parameters"}{"elow"}{$SasPackage}{"Parameters"}="node4.html#363";
$SasIndex{"Parameters"}{"binds"}{$SasPackage}{"Parameters"}="node4.html#398";
$SasIndex{"Parameters"}{"clobber"}{$SasPackage}{"Parameters"}="node4.html#426";

1; # This must be the last line
