# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Columns"}{"FTCOARSE"}{$SasPackage}{"Input Files"}="node7.html#463";
$SasIndex{"Columns"}{"QUADRANT"}{$SasPackage}{"Description"}="node3.html#385";
$SasIndex{"Columns"}{"FRAME"}{$SasPackage}{"Input Files"}="node7.html#459";
$SasIndex{"Columns"}{"NDISCLIN"}{$SasPackage}{"Description"}="node3.html#405";
$SasIndex{"Parameters"}{"outset"}{$SasPackage}{"Parameters"}="node5.html#449";
$SasIndex{"Blocks"}{"PNAUX2"}{$SasPackage}{"Input Files"}="node7.html#471";
$SasIndex{"Columns"}{"NABOVE"}{$SasPackage}{"Description"}="node3.html#399";
$SasIndex{"Parameters"}{"set"}{$SasPackage}{"Parameters"}="node5.html#442";
$SasIndex{"Columns"}{"MCOMMODE"}{$SasPackage}{"Description"}="node3.html#407";
$SasIndex{"Columns"}{"FTFINE"}{$SasPackage}{"Input Files"}="node7.html#465";
$SasIndex{"Columns"}{"NDEFA"}{$SasPackage}{"Description"}="node3.html#401";
$SasIndex{"Tasks"}{"tabgtigen"}{$SasPackage}{"Description"}="node3.html#378";
$SasIndex{"Blocks"}{"PNAUX1"}{$SasPackage}{"Input Files"}="node7.html#457";
$SasIndex{"Tasks"}{"epauxcomb"}{$SasPackage}{"Description"}="node3.html#395";
$SasIndex{"Columns"}{"CYCLE"}{$SasPackage}{"Description"}="node3.html#383";
$SasIndex{"Columns"}{"CCDID"}{$SasPackage}{"Input Files"}="node7.html#469";
$SasIndex{"Columns"}{"NEPDH"}{$SasPackage}{"Description"}="node3.html#403";

1; # This must be the last line
