# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"prefix"}{$SasPackage}{"Parameters"}="node4.html#402";
$SasIndex{"Parameters"}{"quad1-4"}{$SasPackage}{"Parameters"}="node4.html#456";
$SasIndex{"Parameters"}{"region"}{$SasPackage}{"Parameters"}="node4.html#416";
$SasIndex{"Parameters"}{"elow"}{$SasPackage}{"Parameters"}="node4.html#436";
$SasIndex{"Parameters"}{"mask"}{$SasPackage}{"Parameters"}="node4.html#425";
$SasIndex{"Parameters"}{"ehigh"}{$SasPackage}{"Parameters"}="node4.html#446";
$SasIndex{"Parameters"}{"caldb"}{$SasPackage}{"Parameters"}="node4.html#409";

1; # This must be the last line
