# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"count"}{$SasPackage}{"Parameters"}="node4.html#274";
$SasIndex{"Parameters"}{"table"}{$SasPackage}{"Parameters"}="node4.html#288";
$SasIndex{"Parameters"}{"from"}{$SasPackage}{"Parameters"}="node4.html#281";
$SasIndex{"Parameters"}{"withcount"}{$SasPackage}{"Parameters"}="node4.html#295";

1; # This must be the last line
