# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Columns"}{"Y"}{$SasPackage}{"Background correction"}="node11.html#494";
$SasIndex{"Parameters"}{"outeventset"}{$SasPackage}{"Parameters"}="node13.html#542";
$SasIndex{"Tasks"}{"backcorr"}{$SasPackage}{"Background correction"}="node11.html#488";
$SasIndex{"Parameters"}{"ineventset"}{$SasPackage}{"Parameters"}="node13.html#528";
$SasIndex{"EventAttributes"}{"OUT_OF_CCD_WINDOW"}{$SasPackage}{"Comments"}="node18.html#639";
$SasIndex{"Columns"}{"X"}{$SasPackage}{"Background correction"}="node11.html#492";
$SasIndex{"Columns"}{"DETX"}{$SasPackage}{"Introduction"}="node4.html#437";
$SasIndex{"Columns"}{"CCDNR"}{$SasPackage}{"Input Files"}="node15.html#610";
$SasIndex{"Columns"}{"RATE"}{$SasPackage}{"Spectral analysis"}="node7.html#474";
$SasIndex{"Blocks"}{"EXPOSURE"}{$SasPackage}{"Output Files"}="node16.html#627";
$SasIndex{"Errors"}{"copyData01"}{$SasPackage}{"Errors"}="node14.html#583";
$SasIndex{"Blocks"}{"EVENTS"}{$SasPackage}{"Input Files"}="node15.html#592";
$SasIndex{"Tasks"}{"eexpmap"}{$SasPackage}{"Introduction"}="node4.html#445";
$SasIndex{"Parameters"}{"newoutput"}{$SasPackage}{"Parameters"}="node13.html#535";
$SasIndex{"Tasks"}{"evselect"}{$SasPackage}{"Spectral analysis"}="node7.html#460";
$SasIndex{"Columns"}{"PATTERN"}{$SasPackage}{"Assumptions"}="node10.html#484";
$SasIndex{"Tasks"}{"evigweight"}{$SasPackage}{"Introduction"}="node4.html#433";
$SasIndex{"Columns"}{"RAWY"}{$SasPackage}{"Input Files"}="node15.html#602";
$SasIndex{"Columns"}{"RAWX"}{$SasPackage}{"Input Files"}="node15.html#600";
$SasIndex{"Columns"}{"STAT_ERR"}{$SasPackage}{"Spectral analysis"}="node7.html#476";
$SasIndex{"Parameters"}{"witheffectivearea"}{$SasPackage}{"Parameters"}="node13.html#558";
$SasIndex{"Columns"}{"PI"}{$SasPackage}{"Input Files"}="node15.html#594";
$SasIndex{"Parameters"}{"withquantumefficiency"}{$SasPackage}{"Parameters"}="node13.html#572";
$SasIndex{"EventAttributes"}{"OUT_OF_FOV"}{$SasPackage}{"Comments"}="node18.html#637";
$SasIndex{"Tasks"}{"rmfgen"}{$SasPackage}{"Spectral analysis"}="node7.html#466";
$SasIndex{"Tasks"}{"emenergy"}{$SasPackage}{"Input Files"}="node15.html#584";
$SasIndex{"Attributes"}{"BACKSCAL"}{$SasPackage}{"Correction for gaps and"}="node12.html#508";
$SasIndex{"Tasks"}{"epevents"}{$SasPackage}{"Input Files"}="node15.html#588";
$SasIndex{"Parameters"}{"weightcolname"}{$SasPackage}{"Parameters"}="node13.html#551";
$SasIndex{"Columns"}{"WEIGHT"}{$SasPackage}{"Event processing"}="node6.html#457";
$SasIndex{"EventAttributes"}{"OUTSIDE_THRESHOLDS"}{$SasPackage}{"Comments"}="node18.html#641";
$SasIndex{"Tasks"}{"evlistcomb"}{$SasPackage}{"Input Files"}="node15.html#604";
$SasIndex{"Tasks"}{"arfgen"}{$SasPackage}{"Introduction"}="node4.html#449";
$SasIndex{"Columns"}{"DETY"}{$SasPackage}{"Introduction"}="node4.html#439";
$SasIndex{"Parameters"}{"withfiltertransmission"}{$SasPackage}{"Parameters"}="node13.html#565";
$SasIndex{"Tasks"}{"backscale"}{$SasPackage}{"Background correction"}="node11.html#500";

1; # This must be the last line
