# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"maxpofferr"}{$SasPackage}{"Parameters"}="node7.html#428";
$SasIndex{"Errors"}{"missingColumn"}{$SasPackage}{"Errors"}="node8.html#476";
$SasIndex{"Parameters"}{"srclistset"}{$SasPackage}{"Parameters"}="node7.html#386";
$SasIndex{"Errors"}{"obsmliNotTable"}{$SasPackage}{"Errors"}="node8.html#491";
$SasIndex{"Warnings"}{"tooManyPairs"}{$SasPackage}{"Errors"}="node8.html#496";
$SasIndex{"Errors"}{"missingKeyword"}{$SasPackage}{"Errors"}="node8.html#481";
$SasIndex{"Warnings"}{"invalidDateObs"}{$SasPackage}{"Errors"}="node8.html#466";
$SasIndex{"Errors"}{"fitsioError"}{$SasPackage}{"Errors"}="node8.html#451";
$SasIndex{"Errors"}{"missingOBSMLI"}{$SasPackage}{"Errors"}="node8.html#486";
$SasIndex{"Parameters"}{"astcorr"}{$SasPackage}{"Parameters"}="node7.html#435";
$SasIndex{"Parameters"}{"mingood"}{$SasPackage}{"Parameters"}="node7.html#400";
$SasIndex{"Errors"}{"missingExtract"}{$SasPackage}{"Errors"}="node8.html#471";
$SasIndex{"Parameters"}{"catset"}{$SasPackage}{"Parameters"}="node7.html#393";
$SasIndex{"Parameters"}{"syserr"}{$SasPackage}{"Parameters"}="node7.html#421";
$SasIndex{"Warnings"}{"ibinUnexpectedlyLarge"}{$SasPackage}{"Errors"}="node8.html#461";
$SasIndex{"Parameters"}{"minfit"}{$SasPackage}{"Parameters"}="node7.html#407";
$SasIndex{"Parameters"}{"maxoffset"}{$SasPackage}{"Parameters"}="node7.html#414";
$SasIndex{"Warnings"}{"alreadyCorrected"}{$SasPackage}{"Errors"}="node8.html#446";
$SasIndex{"Errors"}{"ibinTooLarge"}{$SasPackage}{"Errors"}="node8.html#456";

1; # This must be the last line
