# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"scale"}{$SasPackage}{"Parameters"}="node4.html#365";
$SasIndex{"Parameters"}{"inmask"}{$SasPackage}{"Parameters"}="node4.html#334";
$SasIndex{"Parameters"}{"prefix"}{$SasPackage}{"Parameters"}="node4.html#327";
$SasIndex{"Parameters"}{"clobber"}{$SasPackage}{"Parameters"}="node4.html#386";
$SasIndex{"Parameters"}{"maxlikelim"}{$SasPackage}{"Parameters"}="node4.html#379";
$SasIndex{"Parameters"}{"flimtot"}{$SasPackage}{"Parameters"}="node4.html#341";
$SasIndex{"Parameters"}{"seper"}{$SasPackage}{"Parameters"}="node4.html#372";
$SasIndex{"Parameters"}{"flimhard"}{$SasPackage}{"Parameters"}="node4.html#357";
$SasIndex{"Parameters"}{"srclist"}{$SasPackage}{"Parameters"}="node4.html#319";
$SasIndex{"Parameters"}{"flimsoft"}{$SasPackage}{"Parameters"}="node4.html#349";

1; # This must be the last line
