# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"outset"}{$SasPackage}{"Parameters"}="node4.html#264";
$SasIndex{"Parameters"}{"set"}{$SasPackage}{"Parameters"}="node4.html#271";

1; # This must be the last line
