# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Errors"}{"InvalidSrcList"}{$SasPackage}{"Errors"}="node5.html#365";
$SasIndex{"Columns"}{"CHANNEL"}{$SasPackage}{"Description"}="node3.html#314";
$SasIndex{"Parameters"}{"output"}{$SasPackage}{"Parameters"}="node4.html#354";
$SasIndex{"Parameters"}{"dec"}{$SasPackage}{"Parameters"}="node4.html#340";
$SasIndex{"Warnings"}{"MultipleSourcesFound"}{$SasPackage}{"Errors"}="node5.html#375";
$SasIndex{"Columns"}{"SPEC_NUM"}{$SasPackage}{"Description"}="node3.html#312";
$SasIndex{"Tasks"}{"om2pha"}{$SasPackage}{"Description"}="node3.html#308";
$SasIndex{"Columns"}{"ROWID"}{$SasPackage}{"Description"}="node3.html#322";
$SasIndex{"Columns"}{"RESPFILE"}{$SasPackage}{"Description"}="node3.html#320";
$SasIndex{"Parameters"}{"srclist"}{$SasPackage}{"Parameters"}="node4.html#326";
$SasIndex{"Parameters"}{"ra"}{$SasPackage}{"Parameters"}="node4.html#333";
$SasIndex{"Parameters"}{"tolerance"}{$SasPackage}{"Parameters"}="node4.html#347";
$SasIndex{"Columns"}{"RATE"}{$SasPackage}{"Description"}="node3.html#316";
$SasIndex{"Errors"}{"NoSourceFound"}{$SasPackage}{"Errors"}="node5.html#370";
$SasIndex{"Columns"}{"STAT_ERR"}{$SasPackage}{"Description"}="node3.html#318";

1; # This must be the last line
