# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Errors"}{"badDataStyle"}{$SasPackage}{"Errors"}="node8.html#823";
$SasIndex{"Columns"}{"IMAGEX"}{$SasPackage}{"FITS file positions"}="node5.html#561";
$SasIndex{"Columns"}{"FLAG"}{$SasPackage}{"FITS file positions"}="node5.html#551";
$SasIndex{"Errors"}{"badCalInfoStyle"}{$SasPackage}{"Errors"}="node8.html#802";
$SasIndex{"Parameters"}{"datetime"}{$SasPackage}{"Parameters"}="node7.html#756";
$SasIndex{"Parameters"}{"ccd"}{$SasPackage}{"Parameters"}="node7.html#685";
$SasIndex{"Columns"}{"DEC"}{$SasPackage}{"FITS file positions"}="node5.html#559";
$SasIndex{"Parameters"}{"calinfostyle"}{$SasPackage}{"Parameters"}="node7.html#721";
$SasIndex{"Parameters"}{"scattapos"}{$SasPackage}{"Parameters"}="node7.html#787";
$SasIndex{"Attributes"}{"DEC_PNT"}{$SasPackage}{"Input Files"}="node9.html#864";
$SasIndex{"Warnings"}{"notOnChip"}{$SasPackage}{"Errors"}="node8.html#837";
$SasIndex{"Errors"}{"badNodeStr"}{$SasPackage}{"Errors"}="node8.html#809";
$SasIndex{"Columns"}{"CCDNR"}{$SasPackage}{"FITS file positions"}="node5.html#538";
$SasIndex{"Attributes"}{"DATE-OBS"}{$SasPackage}{"Task requirements."}="node6.html#587";
$SasIndex{"Parameters"}{"outtab"}{$SasPackage}{"Parameters"}="node7.html#648";
$SasIndex{"Columns"}{"RAWX"}{$SasPackage}{"FITS file positions"}="node5.html#534";
$SasIndex{"Columns"}{"X"}{$SasPackage}{"FITS file positions"}="node5.html#565";
$SasIndex{"Parameters"}{"intab"}{$SasPackage}{"Parameters"}="node7.html#624";
$SasIndex{"Parameters"}{"mosccdnode"}{$SasPackage}{"Parameters"}="node7.html#712";
$SasIndex{"Tasks"}{"cifbuild"}{$SasPackage}{"Task requirements."}="node6.html#597";
$SasIndex{"Parameters"}{"datastyle"}{$SasPackage}{"Parameters"}="node7.html#601";
$SasIndex{"Tasks"}{"param"}{$SasPackage}{"Command-line position entry."}="node4.html#519";
$SasIndex{"Attributes"}{"INSTRUME"}{$SasPackage}{"Task requirements."}="node6.html#585";
$SasIndex{"Tasks"}{"edet2sky"}{$SasPackage}{"Description"}="node3.html#508";
$SasIndex{"Attributes"}{"RA_PNT"}{$SasPackage}{"Input Files"}="node9.html#862";
$SasIndex{"Attributes"}{"PA_PNT"}{$SasPackage}{"Input Files"}="node9.html#866";
$SasIndex{"Parameters"}{"instrument"}{$SasPackage}{"Parameters"}="node7.html#747";
$SasIndex{"Columns"}{"RA"}{$SasPackage}{"FITS file positions"}="node5.html#557";
$SasIndex{"Parameters"}{"scattdec"}{$SasPackage}{"Parameters"}="node7.html#776";
$SasIndex{"Errors"}{"emptyTableName"}{$SasPackage}{"Errors"}="node8.html#830";
$SasIndex{"Columns"}{"RAWY"}{$SasPackage}{"FITS file positions"}="node5.html#547";
$SasIndex{"Parameters"}{"X"}{$SasPackage}{"Parameters"}="node7.html#659";
$SasIndex{"Columns"}{"DETX"}{$SasPackage}{"FITS file positions"}="node5.html#529";
$SasIndex{"Parameters"}{"withouttab"}{$SasPackage}{"Parameters"}="node7.html#633";
$SasIndex{"Columns"}{"IMAGEY"}{$SasPackage}{"FITS file positions"}="node5.html#563";
$SasIndex{"Errors"}{"badInpUnit"}{$SasPackage}{"Errors"}="node8.html#816";
$SasIndex{"Parameters"}{"withheader"}{$SasPackage}{"Parameters"}="node7.html#696";
$SasIndex{"Parameters"}{"calinfoset"}{$SasPackage}{"Parameters"}="node7.html#740";
$SasIndex{"Parameters"}{"Y"}{$SasPackage}{"Parameters"}="node7.html#672";
$SasIndex{"Columns"}{"Y"}{$SasPackage}{"FITS file positions"}="node5.html#567";
$SasIndex{"Parameters"}{"scattra"}{$SasPackage}{"Parameters"}="node7.html#765";
$SasIndex{"Columns"}{"DETY"}{$SasPackage}{"FITS file positions"}="node5.html#531";

1; # This must be the last line
