# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Warnings"}{"label"}{$SasPackage}{"Errors"}="node5.html#278";
$SasIndex{"Errors"}{"label"}{$SasPackage}{"Errors"}="node5.html#273";
$SasIndex{"Parameters"}{"wdxset"}{$SasPackage}{"Parameters"}="node4.html#262";

1; # This must be the last line
