# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"dirfile"}{$SasPackage}{"Parameters"}="node4.html#377";
$SasIndex{"Parameters"}{"coord"}{$SasPackage}{"Parameters"}="node4.html#394";
$SasIndex{"Parameters"}{"elow"}{$SasPackage}{"Parameters"}="node4.html#436";
$SasIndex{"Parameters"}{"pixelsize"}{$SasPackage}{"Parameters"}="node4.html#415";
$SasIndex{"Parameters"}{"ehigh"}{$SasPackage}{"Parameters"}="node4.html#443";
$SasIndex{"Parameters"}{"xdim"}{$SasPackage}{"Parameters"}="node4.html#460";
$SasIndex{"Parameters"}{"alpha"}{$SasPackage}{"Parameters"}="node4.html#429";
$SasIndex{"Parameters"}{"clobber"}{$SasPackage}{"Parameters"}="node4.html#474";
$SasIndex{"Parameters"}{"component"}{$SasPackage}{"Parameters"}="node4.html#422";
$SasIndex{"Parameters"}{"caldb"}{$SasPackage}{"Parameters"}="node4.html#370";
$SasIndex{"Parameters"}{"ydim"}{$SasPackage}{"Parameters"}="node4.html#467";
$SasIndex{"Parameters"}{"crvaln2"}{$SasPackage}{"Parameters"}="node4.html#408";
$SasIndex{"Parameters"}{"crvaln1"}{$SasPackage}{"Parameters"}="node4.html#401";
$SasIndex{"Parameters"}{"maskcontrol"}{$SasPackage}{"Parameters"}="node4.html#450";

1; # This must be the last line
