# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"badpixlocation"}{$SasPackage}{"Parameters"}="node4.html#295";
$SasIndex{"Parameters"}{"useodfatt"}{$SasPackage}{"Parameters"}="node4.html#309";
$SasIndex{"Parameters"}{"spectrumset"}{$SasPackage}{"Parameters"}="node4.html#288";
$SasIndex{"Parameters"}{"withbadpixcorr"}{$SasPackage}{"Parameters"}="node4.html#302";
$SasIndex{"Tasks"}{"arfgen"}{$SasPackage}{"Errors"}="node5.html#327";
$SasIndex{"Parameters"}{"ignoreoutoffov"}{$SasPackage}{"Parameters"}="node4.html#316";
$SasIndex{"Tasks"}{"backscale"}{$SasPackage}{"Errors"}="node5.html#323";

1; # This must be the last line
