# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"outputFileName"}{$SasPackage}{"Parameters"}="node4.html#304";
$SasIndex{"Tasks"}{"odfParamCreator"}{$SasPackage}{"Home Page"}="odfParamCreator.html#276";
$SasIndex{"Tasks"}{"xmmextractor"}{$SasPackage}{"Home Page"}="odfParamCreator.html#280";

1; # This must be the last line
