# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"mask"}{$SasPackage}{"Parameters"}="node4.html#304";
$SasIndex{"Parameters"}{"prefix"}{$SasPackage}{"Parameters"}="node4.html#297";
$SasIndex{"Parameters"}{"clobber"}{$SasPackage}{"Parameters"}="node4.html#332";
$SasIndex{"Parameters"}{"elow"}{$SasPackage}{"Parameters"}="node4.html#311";
$SasIndex{"Parameters"}{"ehigh"}{$SasPackage}{"Parameters"}="node4.html#318";
$SasIndex{"Parameters"}{"mode"}{$SasPackage}{"Parameters"}="node4.html#325";

1; # This must be the last line
