# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"optionalparam"}{$SasPackage}{"Parameters"}="node4.html#274";
$SasIndex{"Warnings"}{"label"}{$SasPackage}{"Errors"}="node5.html#290";
$SasIndex{"Errors"}{"label"}{$SasPackage}{"Errors"}="node5.html#285";
$SasIndex{"Parameters"}{"mandatoryparam"}{$SasPackage}{"Parameters"}="node4.html#267";

1; # This must be the last line
