# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Columns"}{"GRADE"}{$SasPackage}{"Input Files"}="node6.html#451";
$SasIndex{"Parameters"}{"withoffset"}{$SasPackage}{"Parameters"}="node4.html#369";
$SasIndex{"Blocks"}{"EXPOSURE"}{$SasPackage}{"Input Files"}="node6.html#418";
$SasIndex{"Tasks"}{"rgsframes"}{$SasPackage}{"Home Page"}="rgsenergy.html#337";
$SasIndex{"Attributes"}{"WINDOWDX"}{$SasPackage}{"Input Files"}="node6.html#430";
$SasIndex{"Parameters"}{"withdiagoffset"}{$SasPackage}{"Parameters"}="node4.html#392";
$SasIndex{"Parameters"}{"withgain"}{$SasPackage}{"Parameters"}="node4.html#399";
$SasIndex{"Parameters"}{"ccdset"}{$SasPackage}{"Parameters"}="node4.html#357";
$SasIndex{"Attributes"}{"WINDOWDY"}{$SasPackage}{"Input Files"}="node6.html#432";
$SasIndex{"Attributes"}{"RAWY"}{$SasPackage}{"Input Files"}="node6.html#434";
$SasIndex{"Columns"}{"RAWY"}{$SasPackage}{"Input Files"}="node6.html#441";
$SasIndex{"Columns"}{"CCDNODE"}{$SasPackage}{"Input Files"}="node6.html#446";
$SasIndex{"Columns"}{"PI"}{$SasPackage}{"Home Page"}="rgsenergy.html#341";
$SasIndex{"Columns"}{"ENERGY"}{$SasPackage}{"Input Files"}="node6.html#444";
$SasIndex{"Columns"}{"RAWX"}{$SasPackage}{"Input Files"}="node6.html#439";
$SasIndex{"Blocks"}{"PIXELS"}{$SasPackage}{"Home Page"}="rgsenergy.html#343";
$SasIndex{"Columns"}{"SHAPE"}{$SasPackage}{"Input Files"}="node6.html#448";
$SasIndex{"Parameters"}{"withcti"}{$SasPackage}{"Parameters"}="node4.html#406";
$SasIndex{"Attributes"}{"WINDOWX0"}{$SasPackage}{"Input Files"}="node6.html#426";
$SasIndex{"Parameters"}{"offset"}{$SasPackage}{"Parameters"}="node4.html#383";
$SasIndex{"Columns"}{"TIME"}{$SasPackage}{"Input Files"}="node6.html#422";
$SasIndex{"Attributes"}{"WINDOWY0"}{$SasPackage}{"Input Files"}="node6.html#428";
$SasIndex{"Columns"}{"FRAME"}{$SasPackage}{"Input Files"}="node6.html#420";
$SasIndex{"Tasks"}{"rgsoffsetcalc"}{$SasPackage}{"Parameters"}="node4.html#379";

1; # This must be the last line
