# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Errors"}{"No CCD 9 data"}{$SasPackage}{"Errors"}="node5.html#327";
$SasIndex{"Parameters"}{"table"}{$SasPackage}{"Parameters"}="node4.html#283";
$SasIndex{"Parameters"}{"backgroundmodelset"}{$SasPackage}{"Parameters"}="node4.html#311";
$SasIndex{"Parameters"}{"pdistincl"}{$SasPackage}{"Parameters"}="node4.html#297";
$SasIndex{"Parameters"}{"order"}{$SasPackage}{"Parameters"}="node4.html#290";
$SasIndex{"Errors"}{"incompatible event file"}{$SasPackage}{"Errors"}="node5.html#322";
$SasIndex{"Parameters"}{"binningunits"}{$SasPackage}{"Parameters"}="node4.html#304";

1; # This must be the last line
