# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Warnings"}{"The file name will be overwritten"}{$SasPackage}{"Errors"}="node8.html#664";
$SasIndex{"Errors"}{"Could not load column from SRCLIST table-"}{$SasPackage}{"Errors"}="node8.html#649";
$SasIndex{"Parameters"}{"srclistset"}{$SasPackage}{"Parameters"}="node7.html#604";
$SasIndex{"Parameters"}{"outset"}{$SasPackage}{"Parameters"}="node7.html#620";
$SasIndex{"Parameters"}{"set"}{$SasPackage}{"Parameters"}="node7.html#612";
$SasIndex{"Errors"}{"File does not exist"}{$SasPackage}{"Errors"}="node8.html#639";
$SasIndex{"Errors"}{"Unable to load SRCLIST table parameters"}{$SasPackage}{"Errors"}="node8.html#659";
$SasIndex{"Errors"}{"No SRCLIST table in file"}{$SasPackage}{"Errors"}="node8.html#654";
$SasIndex{"Parameters"}{"mode"}{$SasPackage}{"Parameters"}="node7.html#628";
$SasIndex{"Warnings"}{"The SRCLIST table in file name has zero rows- exiting"}{$SasPackage}{"Errors"}="node8.html#670";
$SasIndex{"Errors"}{"Could not open file"}{$SasPackage}{"Errors"}="node8.html#644";

1; # This must be the last line
