# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Columns"}{"DETY"}{$SasPackage}{"Example"}="node3.html#289";
$SasIndex{"Columns"}{"TIME"}{$SasPackage}{"Example"}="node3.html#284";
$SasIndex{"Parameters"}{"table"}{$SasPackage}{"Parameters"}="node4.html#292";
$SasIndex{"Columns"}{"DETX"}{$SasPackage}{"Example"}="node3.html#287";
$SasIndex{"Warnings"}{"invalidColumnName"}{$SasPackage}{"Errors"}="node5.html#317";
$SasIndex{"Parameters"}{"column"}{$SasPackage}{"Parameters"}="node4.html#299";
$SasIndex{"Parameters"}{"resultfile"}{$SasPackage}{"Parameters"}="node4.html#306";

1; # This must be the last line
