# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"clobber"}{$SasPackage}{"Parameters"}="node4.html#381";
$SasIndex{"Parameters"}{"elow"}{$SasPackage}{"Parameters"}="node4.html#332";
$SasIndex{"Parameters"}{"mode"}{$SasPackage}{"Parameters"}="node4.html#318";
$SasIndex{"Parameters"}{"detx"}{$SasPackage}{"Parameters"}="node4.html#346";
$SasIndex{"Parameters"}{"prefix"}{$SasPackage}{"Parameters"}="node4.html#325";
$SasIndex{"Parameters"}{"skyy"}{$SasPackage}{"Parameters"}="node4.html#367";
$SasIndex{"Parameters"}{"maskfile"}{$SasPackage}{"Parameters"}="node4.html#374";
$SasIndex{"Parameters"}{"skyx"}{$SasPackage}{"Parameters"}="node4.html#360";
$SasIndex{"Parameters"}{"ehigh"}{$SasPackage}{"Parameters"}="node4.html#339";
$SasIndex{"Parameters"}{"dety"}{$SasPackage}{"Parameters"}="node4.html#353";

1; # This must be the last line
