# This file was automatically generated by SWIG
package DAL_C_lib;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package DAL_C_lib;
bootstrap DAL_C_lib;
var_DAL_C_lib_init();
@EXPORT = qw( );
1;
