# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"plotflux"}{$SasPackage}{"Parameters"}="node4.html#397";
$SasIndex{"Parameters"}{"plotfile"}{$SasPackage}{"Parameters"}="node4.html#376";
$SasIndex{"Parameters"}{"scalebkgplot"}{$SasPackage}{"Parameters"}="node4.html#390";
$SasIndex{"Parameters"}{"regionplotfile"}{$SasPackage}{"Parameters"}="node4.html#404";
$SasIndex{"Warnings"}{"Keywords are missing from the input file"}{$SasPackage}{"Errors"}="node5.html#462";
$SasIndex{"Warnings"}{"Unavailable device type and/or output file"}{$SasPackage}{"Errors"}="node5.html#452";
$SasIndex{"Tasks"}{"omgrism"}{$SasPackage}{"Home Page"}="omgrismplot.html#337";
$SasIndex{"Parameters"}{"spectraregionfile"}{$SasPackage}{"Parameters"}="node4.html#411";
$SasIndex{"Errors"}{"Incorrect RATE extension"}{$SasPackage}{"Errors"}="node5.html#429";
$SasIndex{"Parameters"}{"set"}{$SasPackage}{"Parameters"}="node4.html#359";
$SasIndex{"Tasks"}{"omgrismplot"}{$SasPackage}{"Home Page"}="omgrismplot.html#331";
$SasIndex{"Errors"}{"Unavailable default device type and/or output file"}{$SasPackage}{"Errors"}="node5.html#442";
$SasIndex{"Parameters"}{"binsize"}{$SasPackage}{"Parameters"}="node4.html#383";
$SasIndex{"Errors"}{"Invalid input file"}{$SasPackage}{"Errors"}="node5.html#447";
$SasIndex{"Parameters"}{"rotatedimageset"}{$SasPackage}{"Parameters"}="node4.html#418";
$SasIndex{"Parameters"}{"plotdevice"}{$SasPackage}{"Parameters"}="node4.html#369";
$SasIndex{"Warnings"}{"Number of data points to plot is higher than 500"}{$SasPackage}{"Errors"}="node5.html#457";
$SasIndex{"Errors"}{"Existing output file cannot be overwritten"}{$SasPackage}{"Errors"}="node5.html#437";
$SasIndex{"Attributes"}{"RATE"}{$SasPackage}{"Errors"}="node5.html#431";
$SasIndex{"Tasks"}{"omgrismplotplot"}{$SasPackage}{"Description"}="node3.html#341";

1; # This must be the last line
