# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"bkgwidthright"}{$SasPackage}{"Parameters"}="node13.html#723";
$SasIndex{"Tasks"}{"omprep"}{$SasPackage}{"Header preparation"}="node8.html#549";
$SasIndex{"Parameters"}{"inpdirectory"}{$SasPackage}{"Parameters"}="node13.html#648";
$SasIndex{"Parameters"}{"scalebkgplot"}{$SasPackage}{"Parameters"}="node13.html#783";
$SasIndex{"Parameters"}{"plotflux"}{$SasPackage}{"Parameters"}="node13.html#775";
$SasIndex{"Parameters"}{"outdirectory"}{$SasPackage}{"Parameters"}="node13.html#655";
$SasIndex{"Tasks"}{"omdetect"}{$SasPackage}{"Source detection"}="node11.html#587";
$SasIndex{"Parameters"}{"bkgoffsetright"}{$SasPackage}{"Parameters"}="node13.html#716";
$SasIndex{"Tasks"}{"omgrismplot"}{$SasPackage}{"Output Files"}="node15.html#857";
$SasIndex{"Environments"}{"SAS_ODF"}{$SasPackage}{"Running The Chain"}="node16.html#863";
$SasIndex{"Parameters"}{"bkgwidthleft"}{$SasPackage}{"Parameters"}="node13.html#709";
$SasIndex{"Tasks"}{"omgprep"}{$SasPackage}{"Preparation of the grism"}="node10.html#567";
$SasIndex{"Parameters"}{"extractionmode"}{$SasPackage}{"Parameters"}="node13.html#738";
$SasIndex{"Parameters"}{"spectrumhalfwidth"}{$SasPackage}{"Parameters"}="node13.html#695";
$SasIndex{"Parameters"}{"plotbinsize"}{$SasPackage}{"Parameters"}="node13.html#767";
$SasIndex{"Tasks"}{"omgrism"}{$SasPackage}{"Source detection"}="node11.html#595";
$SasIndex{"Parameters"}{"bkgoffsetleft"}{$SasPackage}{"Parameters"}="node13.html#702";
$SasIndex{"Tasks"}{"odfingest"}{$SasPackage}{"Input Files"}="node14.html#809";
$SasIndex{"Tasks"}{"ommodmap"}{$SasPackage}{"Modulo-8 noise correction"}="node9.html#563";
$SasIndex{"Parameters"}{"comment"}{$SasPackage}{"Parameters"}="node13.html#662";
$SasIndex{"Parameters"}{"removescatteredlight"}{$SasPackage}{"Parameters"}="node13.html#790";
$SasIndex{"Parameters"}{"mod8correction"}{$SasPackage}{"Parameters"}="node13.html#760";
$SasIndex{"Tasks"}{"omcomb"}{$SasPackage}{"Combination of sub-windows in"}="node7.html#541";
$SasIndex{"Parameters"}{"nsigma"}{$SasPackage}{"Parameters"}="node13.html#669";
$SasIndex{"Parameters"}{"spectrumsmoothlength"}{$SasPackage}{"Parameters"}="node13.html#730";
$SasIndex{"Parameters"}{"combine"}{$SasPackage}{"Parameters"}="node13.html#688";
$SasIndex{"Parameters"}{"extractfieldspectra"}{$SasPackage}{"Parameters"}="node13.html#753";
$SasIndex{"Tasks"}{"Omgchain"}{$SasPackage}{"Description"}="node3.html#509";

1; # This must be the last line
