# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Warnings"}{"The radius of the outer background region is too  small (increasing)"}{$SasPackage}{"Errors"}="node5.html#471";
$SasIndex{"Warnings"}{"The output file name is not specified"}{$SasPackage}{"Errors"}="node5.html#456";
$SasIndex{"Parameters"}{"set"}{$SasPackage}{"Parameters"}="node4.html#388";
$SasIndex{"Parameters"}{"innerradius"}{$SasPackage}{"Parameters"}="node4.html#416";
$SasIndex{"Warnings"}{"The radius of the inner background region is too  small (increasing)"}{$SasPackage}{"Errors"}="node5.html#466";
$SasIndex{"Parameters"}{"scalingfactor"}{$SasPackage}{"Parameters"}="node4.html#409";
$SasIndex{"Parameters"}{"scatset"}{$SasPackage}{"Parameters"}="node4.html#395";
$SasIndex{"Errors"}{"NoFile"}{$SasPackage}{"Errors"}="node5.html#441";
$SasIndex{"Warnings"}{"The second file name is not specified"}{$SasPackage}{"Errors"}="node5.html#451";
$SasIndex{"Parameters"}{"outerradius"}{$SasPackage}{"Parameters"}="node4.html#423";
$SasIndex{"Parameters"}{"outset"}{$SasPackage}{"Parameters"}="node4.html#402";
$SasIndex{"Errors"}{"badType"}{$SasPackage}{"Errors"}="node5.html#446";
$SasIndex{"Warnings"}{"The width of the background region is too small  (increasing by 5 pixels)"}{$SasPackage}{"Errors"}="node5.html#461";
$SasIndex{"Parameters"}{"mode"}{$SasPackage}{"Parameters"}="node4.html#430";

1; # This must be the last line
