# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"binning"}{$SasPackage}{"Parameters"}="node4.html#386";
$SasIndex{"Parameters"}{"withpartcontrol"}{$SasPackage}{"Parameters"}="node4.html#394";
$SasIndex{"Parameters"}{"thresholdmasking"}{$SasPackage}{"Parameters"}="node4.html#355";
$SasIndex{"Parameters"}{"withmaskcontrol"}{$SasPackage}{"Parameters"}="node4.html#415";
$SasIndex{"Parameters"}{"clobber"}{$SasPackage}{"Parameters"}="node4.html#437";
$SasIndex{"Parameters"}{"withsoftcontrol"}{$SasPackage}{"Parameters"}="node4.html#401";
$SasIndex{"Parameters"}{"prefix"}{$SasPackage}{"Parameters"}="node4.html#429";
$SasIndex{"Parameters"}{"smoothingcounts"}{$SasPackage}{"Parameters"}="node4.html#348";
$SasIndex{"Parameters"}{"elow"}{$SasPackage}{"Parameters"}="node4.html#372";
$SasIndex{"Parameters"}{"detector"}{$SasPackage}{"Parameters"}="node4.html#362";
$SasIndex{"Parameters"}{"ehigh"}{$SasPackage}{"Parameters"}="node4.html#379";
$SasIndex{"Parameters"}{"withswcxcontrol"}{$SasPackage}{"Parameters"}="node4.html#408";
$SasIndex{"Parameters"}{"maskfile"}{$SasPackage}{"Parameters"}="node4.html#422";

1; # This must be the last line
