# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Tasks"}{"dal"}{$SasPackage}{"Errors"}="node5.html#405";
$SasIndex{"Parameters"}{"gtiset"}{$SasPackage}{"Parameters"}="node4.html#354";
$SasIndex{"Tasks"}{"evselect"}{$SasPackage}{"Output Files"}="node7.html#413";
$SasIndex{"Parameters"}{"table"}{$SasPackage}{"Parameters"}="node4.html#325";
$SasIndex{"Attributes"}{"SUMSHORT"}{$SasPackage}{"Parameters"}="node4.html#394";
$SasIndex{"Parameters"}{"prefraction"}{$SasPackage}{"Parameters"}="node4.html#368";
$SasIndex{"Tasks"}{"selectlib"}{$SasPackage}{"Description"}="node3.html#309";
$SasIndex{"Tasks"}{"param"}{$SasPackage}{"Errors"}="node5.html#409";
$SasIndex{"Attributes"}{"MINGTISZ"}{$SasPackage}{"Parameters"}="node4.html#392";
$SasIndex{"Tasks"}{"tabgtigen"}{$SasPackage}{"Description"}="node3.html#305";
$SasIndex{"Parameters"}{"mingtisize"}{$SasPackage}{"Parameters"}="node4.html#382";
$SasIndex{"Parameters"}{"postfraction"}{$SasPackage}{"Parameters"}="node4.html#375";
$SasIndex{"Parameters"}{"expression"}{$SasPackage}{"Parameters"}="node4.html#347";
$SasIndex{"Parameters"}{"timecolumn"}{$SasPackage}{"Parameters"}="node4.html#361";

1; # This must be the last line
