# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"outset"}{$SasPackage}{"Parameters"}="node5.html#561";
$SasIndex{"Warnings"}{"Not enough bins to process variability tests"}{$SasPackage}{"Errors"}="node6.html#737";
$SasIndex{"Errors"}{"Require new output file name"}{$SasPackage}{"Errors"}="node6.html#727";
$SasIndex{"Errors"}{"Negative count rates in Input File"}{$SasPackage}{"Errors"}="node6.html#717";
$SasIndex{"Warnings"}{"Keyword CONTENT missing in Input File"}{$SasPackage}{"Errors"}="node6.html#742";
$SasIndex{"Warnings"}{"CONTENT parameter for input file is ..."}{$SasPackage}{"Errors"}="node6.html#753";
$SasIndex{"Warnings"}{"HDUCLAS2 is not equal to TOTAL"}{$SasPackage}{"Errors"}="node6.html#791";
$SasIndex{"Parameters"}{"flaretest"}{$SasPackage}{"Parameters"}="node5.html#630";
$SasIndex{"Parameters"}{"gtis"}{$SasPackage}{"Parameters"}="node5.html#578";
$SasIndex{"Parameters"}{"set"}{$SasPackage}{"Parameters"}="node5.html#544";
$SasIndex{"Attributes"}{"TIMEDEL"}{$SasPackage}{"Description"}="node3.html#534";
$SasIndex{"Parameters"}{"newoutset"}{$SasPackage}{"Parameters"}="node5.html#554";
$SasIndex{"Errors"}{"Null or negative Bin Width in Input File"}{$SasPackage}{"Errors"}="node6.html#677";
$SasIndex{"Errors"}{"Negative background values in Input File"}{$SasPackage}{"Errors"}="node6.html#722";
$SasIndex{"Parameters"}{"variationtest"}{$SasPackage}{"Parameters"}="node5.html#651";
$SasIndex{"Errors"}{"Different number of columns between RATE, ERROR, BACKV and BACKE"}{$SasPackage}{"Errors"}="node6.html#685";
$SasIndex{"Parameters"}{"flarefactor"}{$SasPackage}{"Parameters"}="node5.html#637";
$SasIndex{"Errors"}{"Different number of rows in columns between RATE, ERROR, BACKV and BACKE"}{$SasPackage}{"Errors"}="node6.html#693";
$SasIndex{"Parameters"}{"gtiset"}{$SasPackage}{"Parameters"}="node5.html#585";
$SasIndex{"Warnings"}{"Null or negative exposure time in Input File"}{$SasPackage}{"Errors"}="node6.html#824";
$SasIndex{"Errors"}{"Keyword TIMEDEL missing in Input File"}{$SasPackage}{"Errors"}="node6.html#669";
$SasIndex{"Warnings"}{"Keyword TSTART missing in GTI File"}{$SasPackage}{"Errors"}="node6.html#832";
$SasIndex{"Parameters"}{"percentage"}{$SasPackage}{"Parameters"}="node5.html#658";
$SasIndex{"Warnings"}{"Keyword TSTART missing in Input"}{$SasPackage}{"Errors"}="node6.html#802";
$SasIndex{"Parameters"}{"netlightcurve"}{$SasPackage}{"Parameters"}="node5.html#623";
$SasIndex{"Errors"}{"Can not carry out two distribution KS test and chi-squared test"}{$SasPackage}{"Errors"}="node6.html#732";
$SasIndex{"Warnings"}{"HDUCLAS is not equal to OGIP"}{$SasPackage}{"Errors"}="node6.html#769";
$SasIndex{"Parameters"}{"twodists"}{$SasPackage}{"Parameters"}="node5.html#602";
$SasIndex{"Tasks"}{"epiclccorr"}{$SasPackage}{"Home Page"}="ekstest.html#498";
$SasIndex{"Warnings"}{"Keyword TSTOP missing in GTI File"}{$SasPackage}{"Errors"}="node6.html#843";
$SasIndex{"Warnings"}{"HDUCLAS1 is not equal to LIGHTCURVE"}{$SasPackage}{"Errors"}="node6.html#780";
$SasIndex{"Errors"}{"No data point received"}{$SasPackage}{"Errors"}="node6.html#709";
$SasIndex{"Parameters"}{"kstest"}{$SasPackage}{"Parameters"}="node5.html#595";
$SasIndex{"Tasks"}{"tabgtigen"}{$SasPackage}{"Home Page"}="ekstest.html#502";
$SasIndex{"Warnings"}{"Keyword EXPOSURE missing in Input File"}{$SasPackage}{"Errors"}="node6.html#813";
$SasIndex{"Errors"}{"Number of light-curves contained in a file must not exceed 9"}{$SasPackage}{"Errors"}="node6.html#701";
$SasIndex{"Parameters"}{"fracvartest"}{$SasPackage}{"Parameters"}="node5.html#616";
$SasIndex{"Parameters"}{"chisquaretest"}{$SasPackage}{"Parameters"}="node5.html#609";
$SasIndex{"Tasks"}{"ekstest"}{$SasPackage}{"Home Page"}="ekstest.html#492";
$SasIndex{"Parameters"}{"flarebins"}{$SasPackage}{"Parameters"}="node5.html#644";
$SasIndex{"Tasks"}{"elcbuild"}{$SasPackage}{"Description"}="node3.html#516";
$SasIndex{"Parameters"}{"screen"}{$SasPackage}{"Parameters"}="node5.html#571";
$SasIndex{"Warnings"}{"Keyword HDUCLASS missing in Input File"}{$SasPackage}{"Errors"}="node6.html#758";

1; # This must be the last line
