# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"func"}{$SasPackage}{"Parameters"}="node4.html#258";
$SasIndex{"Parameters"}{"min_src_flux"}{$SasPackage}{"Parameters"}="node4.html#265";
$SasIndex{"Parameters"}{"index"}{$SasPackage}{"Parameters"}="node4.html#279";
$SasIndex{"Parameters"}{"cxrb_norm"}{$SasPackage}{"Parameters"}="node4.html#272";

1; # This must be the last line
