# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"inmask"}{$SasPackage}{"Parameters"}="node4.html#288";
$SasIndex{"Parameters"}{"reglist"}{$SasPackage}{"Parameters"}="node4.html#302";
$SasIndex{"Parameters"}{"inimage"}{$SasPackage}{"Parameters"}="node4.html#281";
$SasIndex{"Parameters"}{"clobber"}{$SasPackage}{"Parameters"}="node4.html#309";
$SasIndex{"Parameters"}{"outmask"}{$SasPackage}{"Parameters"}="node4.html#295";

1; # This must be the last line
