# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Tasks"}{"multixmmselect"}{$SasPackage}{"Description"}="node3.html#309";
$SasIndex{"Parameters"}{"bkg"}{$SasPackage}{"Parameters"}="node4.html#356";
$SasIndex{"Errors"}{"specChannelIntervalError"}{$SasPackage}{"Errors"}="node5.html#407";
$SasIndex{"Parameters"}{"filebkg"}{$SasPackage}{"Parameters"}="node4.html#384";
$SasIndex{"Errors"}{"pairing"}{$SasPackage}{"Errors"}="node5.html#402";
$SasIndex{"Parameters"}{"pha"}{$SasPackage}{"Parameters"}="node4.html#349";
$SasIndex{"Parameters"}{"filepha"}{$SasPackage}{"Parameters"}="node4.html#377";
$SasIndex{"Tasks"}{"multiespecget"}{$SasPackage}{"Description"}="node3.html#313";
$SasIndex{"Parameters"}{"rmf"}{$SasPackage}{"Parameters"}="node4.html#363";
$SasIndex{"Tasks"}{"epicspeccombine"}{$SasPackage}{"Description"}="node3.html#305";
$SasIndex{"Parameters"}{"filersp"}{$SasPackage}{"Parameters"}="node4.html#391";
$SasIndex{"Tasks"}{"epicespeccombine"}{$SasPackage}{"Description"}="node3.html#329";
$SasIndex{"Parameters"}{"arf"}{$SasPackage}{"Parameters"}="node4.html#370";

1; # This must be the last line
