# This file is automatically generated by SAS
# DO NOT EDIT!

$SasIndex{"Parameters"}{"catfile"}{$SasPackage}{"Parameters"}="node8.html#410";
$SasIndex{"Errors"}{"diffBin"}{$SasPackage}{"Errors"}="node9.html#449";
$SasIndex{"Warnings"}{"Too few guide stars for astrometry correction"}{$SasPackage}{"Errors"}="node9.html#487";
$SasIndex{"Parameters"}{"maxradecerr"}{$SasPackage}{"Parameters"}="node8.html#417";
$SasIndex{"Parameters"}{"rotateimage"}{$SasPackage}{"Parameters"}="node8.html#438";
$SasIndex{"Parameters"}{"sourcelistset"}{$SasPackage}{"Parameters"}="node8.html#389";
$SasIndex{"Warnings"}{"Star catalogue not found -- no astrometry correction done"}{$SasPackage}{"Errors"}="node9.html#467";
$SasIndex{"Parameters"}{"set"}{$SasPackage}{"Parameters"}="node8.html#382";
$SasIndex{"Warnings"}{"<"}{$SasPackage}{"Errors"}="node9.html#472";
$SasIndex{"Parameters"}{"maxrmsres"}{$SasPackage}{"Parameters"}="node8.html#424";
$SasIndex{"Warnings"}{"noCat"}{$SasPackage}{"Errors"}="node9.html#477";
$SasIndex{"Parameters"}{"usecat"}{$SasPackage}{"Parameters"}="node8.html#403";
$SasIndex{"Warnings"}{"insuffData"}{$SasPackage}{"Errors"}="node9.html#497";
$SasIndex{"Errors"}{"Could not allocate memory for: <I>name</I>"}{$SasPackage}{"Errors"}="node9.html#461";
$SasIndex{"Parameters"}{"ppsoswset"}{$SasPackage}{"Parameters"}="node8.html#396";
$SasIndex{"Parameters"}{"tolerance"}{$SasPackage}{"Parameters"}="node8.html#431";

1; # This must be the last line
